Feat/cross app navigation
siemens/ix pull request #1007
Opened 2023-12-15 10:54 UTC by danielleroux

## 💡 What is the current behavior?

- Closes #165 

## 🆕 What is the new behavior?

- deprecate basic-navigation and map-navigation
- Remove `@internal` from ix-application, ix-content, ix-application-header
- Add app switch feature to ix-application

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [x] 🦮 Accessibility (a11y) features were implemented
- [x] 🗺️ Internationalization (i18n) - no hard coded strings
- [x] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`yarn docs`)
- [x] 🧪 Unit tests were added/updated and pass (`yarn test`)
- [ ] 📸 Visual regression tests were added/updated and pass (`yarn visual-regression`)
- [ ] 🧐 Static code analysis passes (`yarn lint`)
- [ ] 🏗️ Successful compilation (`yarn build`, changes pushed)

## 👨‍💻 Help & support

2023-12-19 08:15 UTC, nuke-ellington commented on packages/core/src/components/application-header/application-header.tsx
> +  @State() isSlotted = false;
Name is misleading, hasSlottedElements or similar would be better IMO

2023-12-19 10:27 UTC, nuke-ellington requested changes

2023-12-19 10:27 UTC, nuke-ellington commented on packages/documentation/docs/controls/application-frame/_application-menu_code.md
2nd lvl example still has basic navigation. We should remove that

2023-12-19 10:27 UTC, nuke-ellington commented on packages/core/src/components/application-header/application-switch-modal/application-switch-modal.tsx
ESC seems to break the modal

2023-12-19 13:22 UTC, danielleroux commented on packages/core/src/components/application-header/application-switch-modal/application-switch-modal.tsx
Handled via IX-699

2024-01-08 14:33 UTC, nuke-ellington requested changes

2024-01-08 14:33 UTC, nuke-ellington commented on packages/documentation/docs/controls/application-frame/application.md
> +The code snippet blow shows a example of a combination of different components like `ix-application-header` or `ix-content`.
```suggestion
The code snippet blow shows an example of a combination of different components like `ix-application-header` or `ix-content`.
```

2024-01-08 15:26 UTC, nuke-ellington submitted a review, later dismissed

2024-01-09 12:17 UTC, nuke-ellington approved these changes

2024-01-10 05:53 UTC, merged