fix(core/message-bar): remove unwanted margin
siemens/ix pull request #1064
Opened 2024-02-05 09:28 UTC by matthiashader

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [ ] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bug fix
- [ ] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Testing

## Other information

2024-02-16 09:57 UTC, nuke-ellington requested changes
Since a list of message bars should have vertical margins of 0.5rem between the individual bars we should replace the <br> tags with actual margins in the examples.
This will better illustrate the usage to the users.
Also removing the built-in margins is kind of like a breaking change IMO?

2024-02-21 10:44 UTC, matthiashader commented on packages/core/scss/theme/classic-dark/_borderWidth.scss
> +      --theme-message-bar--border-thickness: 0.13rem;
resolved

2024-02-21 10:45 UTC, matthiashader commented on packages/core/scss/theme/classic-light/_borderWidth.scss
> +      --theme-message-bar--border-thickness: 0.13rem;
resolved

2024-02-21 10:46 UTC, matthiashader commented on packages/core/src/components/message-bar/message-bar.scss
> +    font-weight: normal;
this has been remained, according to figma the font weight should be 400 (normal)

2024-02-21 12:45 UTC, nuke-ellington requested changes

2024-02-21 12:45 UTC, nuke-ellington commented on packages/core/src/components/message-bar/message-bar.scss
> -    margin: $small-space $small-space 0rem $small-space;
This will cause a visual breaking change. Pull it up into host element before it can be removed finally in v3.

2024-02-21 12:45 UTC, nuke-ellington commented on packages/angular-test-app/src/preview-examples/message-bar.ts
> +      <ix-message-bar style="margin-bottom: 1.25rem; display: block" type="warning">Message text</ix-message-bar>
Also for the other examples!

```suggestion
      <ix-message-bar style="margin-bottom: 0.5rem; display: block">Message text</ix-message-bar>
      <ix-message-bar style="margin-bottom: 0.5rem; display: block" type="warning">Message text</ix-message-bar>
```

2024-02-22 08:16 UTC, nuke-ellington approved these changes

2024-02-22 08:19 UTC, merged

2024-06-07 14:58 UTC, TDaniel-evo commented
Instead of removing the right and left margins, additional top margin has been added. Is this the expected outcome?
![image](https://github.com/siemens/ix/assets/144789952/9701bf89-1075-4834-8e60-73e2b05b1701)