docs(progress-bar): add guidelines
siemens/ix pull request #1091
Opened 2024-02-15 16:19 UTC by silviowolf

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [ ] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bug fix
- [ ] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: N/A

## What is the new behavior?

- Guidelines added
- 
## Does this introduce a breaking change?

- [x] Yes
- [ ] No

## Testing

## Other information

- dev component and dev doc doesn’t exist yet
- documentation has to be reviewed when component is developed

2024-03-01 10:00 UTC, nuke-ellington requested changes
I think we need to link to a specific button page

2024-03-01 10:00 UTC, nuke-ellington commented on packages/documentation/docs/controls/_progress-bar_styleguide.md
> +- loading option of [Button](./buttons/)
```suggestion
- loading option of [Button](./buttons/button.md)
```

2024-03-01 14:39 UTC, nuke-ellington approved these changes

2025-02-19 09:02 UTC, danielleroux commented
@silviowolf  We will reopen pr again later if we need the guide.

2025-02-19 09:02 UTC, closed without merging