fix(core/897-menu): fix unwanted behavior with active element
siemens/ix pull request #1102
Opened 2024-02-21 09:40 UTC by matthiashader

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [ ] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bug fix
- [ ] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Upon reopening the ix-menu, the ix-category appears expanded but contains no items. Only after collapsing and reopening the ix-menu-category, the menu-items become visible again.
Found a small edge case, where the category does not initially open when the menu is expanded

GitHub Issue Number: #1053

## What is the new behavior?

- after menu is collapsed the style of the menuItemContainer is cleared (max-height / opacity)
- changed up the component lifecycle order (in order to initialize the menuExpanded and showItems, which is initially needed in order to show the activeElemement)

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Testing

## Other information

2024-02-22 09:21 UTC, nuke-ellington requested changes

2024-02-22 09:21 UTC, nuke-ellington commented on packages/core/src/components/menu-category/test/menu-category.ct.ts
A visual regression test is also necessary to ensure that the submenu is rendered correctly.

2024-02-22 15:27 UTC, nuke-ellington commented on packages/core/src/tests/menu/menu.e2e.ts
> +        name: 'Double Chevron Right',
Once #1112 is merged we can change this to:
```suggestion
        name: 'Double Chevron Left',
```

2024-02-23 14:44 UTC, nuke-ellington approved these changes

2024-02-26 06:59 UTC, danielleroux submitted a review, later dismissed

2024-02-26 10:25 UTC, danielleroux approved these changes

2024-02-26 10:25 UTC, merged