Fix/554 menu
siemens/ix pull request #1127
Opened 2024-02-28 08:25 UTC by matthiashader

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [ ] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bug fix
- [ ] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Testing

## Other information

2024-03-01 11:28 UTC, nuke-ellington requested changes
On small viewports the area above the menu items should not be visisble:
<img width="384" alt="Screenshot 2024-03-01 at 11 44 36" src="https://github.com/siemens/ix/assets/14405078/bb094bc6-a1a9-4e03-a79a-7590d9074e97">

This is how it should look instead:
<img width="319" alt="Screenshot 2024-03-01 at 11 48 27" src="https://github.com/siemens/ix/assets/14405078/1aeb67b2-8c9a-431e-9e8f-e4dd14313f8a">

We should add VRTs for all 3 possible viewports

2024-03-05 09:18 UTC, nuke-ellington requested changes

2024-03-05 09:18 UTC, nuke-ellington commented on packages/core/src/tests/application/application.e2e.ts-snapshots/basic-navigation-mobile-mobile-expanded-1-chromium---theme-classic-dark-linux.png
I think the design still has the margin above the top item (Test 1) but it should be part of the scrollable area.

2024-03-06 15:51 UTC, nuke-ellington approved these changes

2024-03-07 13:31 UTC, jul-lam approved these changes

2024-03-07 14:08 UTC, merged