fix(date-dropdown): updated the current date when the props are changed
siemens/ix pull request #1139
Opened 2024-03-01 22:13 UTC by ridvandmrc

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Build (`yarn build`) was run locally and any changes were pushed
- [X] Unit tests (`yarn test`) were run locally and passed
- [X] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [X] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [X] Bug fix
- [ ] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?
date-dropdown can not be set outside of the component

GitHub Issue Number: #1122 

## What is the new behavior?
Fixed and tested

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Testing

## Other information

2024-03-04 10:56 UTC, nuke-ellington requested changes
Looks like this breaks a unit test. Also a test case for the change was not added.

2024-03-12 15:07 UTC, ridvandmrc commented
Hi @nuke-ellington ,
I tested it to much but I can not reproduced

2024-03-28 13:21 UTC, ridvandmrc commented
> > Hi @nuke-ellington , I tested it to much but I can not reproduced
> 
> @ridvandmrc Do you plan to update this PR? Regarding @nuke-ellington change request?
> 
> There are also some debug console log statements inside the component code, you should remove the logs there.

Yes, I plan to update, and I remove every logs

2024-03-29 13:56 UTC, ridvandmrc commented
Hi @danielleroux ,
I updated the test cases and also I added an example for react-sample and also tested manually

2024-04-02 09:12 UTC, danielleroux requested changes

2024-04-02 11:51 UTC, ridvandmrc commented on packages/react-test-app/src/preview-examples/date-dropdown.tsx
Hi @danielleroux,
I was thinking that these examples could be more helpful. 
okay I revert it, you can review again.

2024-04-02 11:53 UTC, danielleroux commented on packages/react-test-app/src/preview-examples/date-dropdown.tsx
Yes they are helpful but you have missed also to adapt the angular, vue and html examples they have to be all the same.

And you have to keep in mind that the examples as to fit into the example iframe window also on different screen sizes.

2024-04-02 12:04 UTC, ridvandmrc commented on packages/react-test-app/src/preview-examples/date-dropdown.tsx
I see thanks a lot

2024-04-03 08:37 UTC, danielleroux submitted a review, later dismissed

2024-04-03 08:49 UTC, danielleroux approved these changes

2024-04-03 09:09 UTC, nuke-ellington requested changes

2024-04-03 09:09 UTC, nuke-ellington commented on .changeset/orange-insects-pull.md
> +fix(core/date-dropdown): update the date when the props are change
```suggestion
fix(core/date-dropdown): update the date when the props are changed
```

2024-04-03 11:50 UTC, nuke-ellington approved these changes

2024-04-03 12:20 UTC, merged