docs: remove "iX" and fix typos
siemens/ix pull request #1150
Opened 2024-03-08 15:38 UTC by silviowolf

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [ ] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bug fix
- [ ] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: N/A

## What is the new behavior?

- remove "iX" abbrevations
- fix typos

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Testing

## Other information

2024-03-08 16:39 UTC, nuke-ellington requested changes

2024-03-08 16:39 UTC, nuke-ellington commented on CONTRIBUTING.md
> +Siemens provides a holistic design system for building attractive and intuitive web applications.
```suggestion
With Industrial Experience Siemens provides a holistic design system for building attractive and intuitive web applications.
```

2024-03-08 16:39 UTC, nuke-ellington commented on CONTRIBUTING.md
> +Please make sure to enable the option `Allow commits from members who can merge to the target branch` in your MR. This way the maintainer team will be able to rebase the MR if necessary.
```suggestion
Please make sure to enable the option `Allow commits from members who can merge to the target branch` in your MR. This way the maintainers will be able to rebase the MR if necessary.
```

2024-03-08 16:39 UTC, nuke-ellington commented on packages/documentation/docs/installation/csp.md
> +With version 3 the Web Component compiler Stencil (used to build all components) introduced support for CSP nonces.
```suggestion
With version 3 the Web Component compiler Stencil (used to build all of our components) introduced support for CSP nonces.
```

2024-03-08 16:39 UTC, nuke-ellington commented on packages/documentation/docs/introduction.md
> +Siemens Industrial Experience provides and maintains a Figma design kit containing all components, design foundations and assets. Multiple code implementations are offered and maintained by the team.
```suggestion
Siemens Industrial Experience provides and maintains a Figma design kit containing all components, design foundations and assets. Multiple code implementations are offered and maintained by our team. With guidelines on UX writing, pattern usage and more, Siemens Industrial Experience supports its users along the way. The comprehensive icon set contains more than 500 icons and is constantly growing.
```

2024-03-08 16:39 UTC, nuke-ellington commented on packages/documentation/docs/migration/2_0_0/index.md
> +### Replacement of Bootstrap Modal parts with ix-modal components
```suggestion
### Replacement of Bootstrap Modal parts with our modal components
```

2024-03-08 16:39 UTC, nuke-ellington commented on packages/aggrid/README.md
> +# AGGrid Theme
```suggestion
# AG Grid Theme
```

2024-03-11 14:14 UTC, nuke-ellington submitted a review, later dismissed

2024-03-25 12:30 UTC, danielleroux approved these changes

2024-03-25 12:30 UTC, merged