fix(core/card): adjust selected background color
siemens/ix pull request #1171
Opened 2024-03-18 10:49 UTC by matthiashader

## 💡 What is the current behavior?

GitHub Issue Number: #<ISSUE NUMBER>

## 🆕 What is the new behavior?

-
-

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`yarn docs`)
- [ ] 🧪 Unit tests were added/updated and pass (`yarn test`)
- [ ] 📸 Visual regression tests were added/updated and pass (`yarn visual-regression`)
- [ ] 🧐 Static code analysis passes (`yarn lint`)
- [ ] 🏗️ Successful compilation (`yarn build`, changes pushed)

## 👨‍💻 Help & support

2024-03-25 15:37 UTC, nuke-ellington requested changes

2024-03-26 14:53 UTC, danielleroux requested changes

2024-03-26 14:53 UTC, danielleroux commented on packages/core/component-doc.json
> -    "typescriptVersion": "5.4.2"
Don't downgrade component-doc.json. Please execute `pnpm install` to install latest dev dependencies.

2024-03-27 07:57 UTC, danielleroux approved these changes

2024-03-27 13:23 UTC, nuke-ellington approved these changes

2024-03-27 13:34 UTC, merged