docs: deploy multiple docs versions
siemens/ix pull request #1177
Opened 2024-03-20 08:38 UTC by danielleroux

## 💡 What is the current behavior?

GitHub Issue Number: #<ISSUE NUMBER>

## 🆕 What is the new behavior?

-
-

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`yarn docs`)
- [ ] 🧪 Unit tests were added/updated and pass (`yarn test`)
- [ ] 📸 Visual regression tests were added/updated and pass (`yarn visual-regression`)
- [ ] 🧐 Static code analysis passes (`yarn lint`)
- [ ] 🏗️ Successful compilation (`yarn build`, changes pushed)

## 👨‍💻 Help & support

2024-03-26 07:13 UTC, danielleroux commented on packages/core/.eslintrc.json
> +  "extends": [/* "plugin:@typescript-eslint/recommended", */ "plugin:@stencil-community/recommended", "ix"],
Nothing for production yet, but should be keep for developement.

2024-03-26 08:33 UTC, nuke-ellington approved these changes

2024-03-26 15:28 UTC, nuke-ellington requested changes

2024-03-26 15:28 UTC, nuke-ellington commented on packages/figma-plugin/src/figma.ts
> +      `🪲 Ups! A received a different status code ${response.status}`,
```suggestion
      `🪲 Oops! Received unexpected status code ${response.status}`,
```

2024-03-27 08:35 UTC, nuke-ellington submitted a review, later dismissed

2024-03-27 09:07 UTC, nuke-ellington approved these changes

2024-03-27 09:12 UTC, merged