fix(core/workflow-steps): fix initial layout shift
siemens/ix pull request #1198
Opened 2024-04-08 11:49 UTC by matthiashader

## 💡 What is the current behavior?

GitHub Issue Number: #<ISSUE NUMBER>

## 🆕 What is the new behavior?

-
-

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [ ] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [ ] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [ ] 🧐 Static code analysis passes (`pnpm lint`)
- [ ] 🏗️ Successful compilation (`pnpm build`, changes pushed)

## 👨‍💻 Help & support

2024-04-15 05:57 UTC, danielleroux requested changes
Could you please add a component test?

2024-04-15 05:57 UTC, danielleroux commented on .changeset/bright-pugs-know.md
> +fix initial layout shift
```suggestion
fix(core/workflow-steps): fix initial layout shift
```

2024-04-16 08:23 UTC, danielleroux approved these changes

2024-04-16 08:24 UTC, merged

2024-04-16 08:25 UTC, matthiashader commented
> Could you please add a component test?

As this fix only affects the componentWillLoad() Lifecycle it is hard to test, because after the mount() (in the component test) componentWillLoad was already called. Also the bug only affected a short flicker at the beginning.