Docs/centralized example styles
siemens/ix pull request #1222
Opened 2024-04-16 13:32 UTC by jul-lam

## 💡 What is the current behavior?

GitHub Issue Number: #<ISSUE NUMBER>

## 🆕 What is the new behavior?

-
-

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [ ] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [ ] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [ ] 🧐 Static code analysis passes (`pnpm lint`)
- [ ] 🏗️ Successful compilation (`pnpm build`, changes pushed)

## 👨‍💻 Help & support

2024-05-07 08:56 UTC, danielleroux requested changes

2024-05-07 08:56 UTC, danielleroux commented on packages/documentation/scripts/generate-markdown.ts
> +        ): Promise<any[]> => {
Make correct time avoid any here

2024-05-07 08:56 UTC, danielleroux commented on packages/documentation/scripts/generate-markdown.ts
> +                path.join(directory, `${entry.name}.txt`)
Why is the .txt postfix necessary?

2024-05-07 08:56 UTC, danielleroux commented on packages/documentation/src/components/PlaygroundV2/utils.ts
> +      `${styleFilePath}global.css.txt`,
Result of the .txt postfix. Looks odd to have .txt file here

2024-05-07 08:56 UTC, danielleroux commented on packages/documentation/src/components/PlaygroundV2/utils.ts
> +        }`,
dont use `yarn`

2024-05-08 08:52 UTC, danielleroux approved these changes

2024-05-08 12:44 UTC, nuke-ellington requested changes

2024-05-08 12:44 UTC, nuke-ellington commented on packages/documentation/src/components/PlaygroundV2/utils.ts
> +    }
This code block is essentially duplicated thrice in this file. Maybe we can extract it with the file suffixes as parameters?

2024-05-14 08:47 UTC, nuke-ellington approved these changes

2024-05-15 07:34 UTC, merged