docs(button): add danger button description
siemens/ix pull request #1223
Opened 2024-04-16 17:44 UTC by silviowolf

## 💡 What is the current behavior?

GitHub Issue Number: #<ISSUE NUMBER>

## 🆕 What is the new behavior?

- add danger button description
- add ellipsis description
- add min-width description

2024-04-18 10:33 UTC, kathrinschalber approved these changes

2024-04-22 11:53 UTC, silviowolf commented on packages/documentation/docs/controls/buttons/_button_styleguide.md
> +- **Ellipsis (...):** We use ellipsis when a button action requires further user input for executing. Example: The button "Connect..." opens a modal with a list of potential connection targets from w
The ellipsis pattern is one of the very classical standards on all usual operating systems used on buttons and menu actions ("Save" vs. "Save as…", "Print" vs. "Print…")

2024-04-23 11:45 UTC, nuke-ellington requested changes

2024-04-23 11:45 UTC, nuke-ellington commented on packages/documentation/docs/controls/buttons/_button_styleguide.md
> +- **Danger button:** We use the danger button variant to emphasize particularly dangerous, destructive or critical actions that cannot easily be undone, consider this especially in confirmation dialo
```suggestion
- **Danger button:** We use the danger button variant to emphasize particularly dangerous, destructive or critical actions that cannot easily be undone,. Consider this especially in confirmation dialogs. 
```

2024-04-23 11:45 UTC, nuke-ellington commented on packages/documentation/docs/controls/buttons/_button_styleguide.md
> +- Don’t only rely on standard buttons when many actions/functions are necessary, consider dropdown, split or menu buttons or moving some functionality to a panel or a dialog
```suggestion
- Don’t only rely on standard buttons when many actions/functions are necessary,. Consider dropdown, split or menu buttons or moving some functionality to a panel or a dialog
```

2024-04-23 11:45 UTC, nuke-ellington commented on packages/documentation/docs/controls/buttons/_button_styleguide.md
> +## Dos and Don’ts
```suggestion
## Dos and Don'ts
```

2024-04-23 11:45 UTC, nuke-ellington commented on packages/documentation/docs/controls/buttons/_button_styleguide.md
> +- Don’t only rely on standard buttons when many actions/functions are necessary, consider dropdown, split or menu buttons or moving some functionality to a panel or a dialog
```suggestion
- Don't use the danger button excessively and repetitively as in lists or tables, use it carefully and very selectively instead
- Don't extend your ghost button width beyond the label’s available width
- Don't only rely on standard buttons when many actions/functions are necessary, consider dropdown, split or menu buttons or moving some functionality to a panel or a dialog
```

2024-04-23 11:45 UTC, nuke-ellington commented on packages/documentation/docs/controls/buttons/_icon-button_styleguide.md
> +All the variants, options and states of the [button](./button.md) component apply to the icon button. We’ve listed additional or deviating specifications here.
```suggestion
All the variants, options and states of the [button](./button.md) component apply to the icon button. We've listed additional or deviating specifications here.
```

2024-04-23 11:45 UTC, nuke-ellington commented on packages/documentation/docs/controls/buttons/_icon-button_styleguide.md
> +## Dos and Don’ts
```suggestion
## Dos and Don'ts
```

2024-04-23 11:45 UTC, nuke-ellington commented on packages/documentation/docs/controls/buttons/_icon-button_styleguide.md
> +- Don’t stretch icon buttons to span a container’s width
```suggestion
- Don't use icon buttons in large numbers, instead use a toolbar
- Don't stretch icon buttons to span a container’s width
```

2024-05-21 09:39 UTC, nuke-ellington approved these changes

2024-05-22 06:34 UTC, merged