fix(documentation): button examples
siemens/ix pull request #127
Opened 2022-11-09 15:10 UTC by goncalosard

## Summary

Button examples added to the documentation. 

Build failed because of file component-doc.json because i'm developing on windows device. 
Works perfectly on my device.
Please run this branch on your device and add the file again, it should fix the problem.

## How did you test this change?

Tested locally

2022-11-11 08:38 UTC, nuke-ellington requested changes
The button page should be structured similar to the zeplin specs page with separate section per class (e.g. Primary buttons, Secondary..).

2022-11-18 06:37 UTC, danielleroux commented
@silviowolf can you give us feedback regarding the button namings in figma? This PR is depending on it.

2022-11-18 08:44 UTC, danielleroux commented
I renamed the button page togther with @silviowolf 

@nuke-ellington Can you please to a review

2022-11-18 09:20 UTC, nuke-ellington approved these changes

2022-11-18 09:21 UTC, merged