fix(core/select): rollback and fix object iteration
siemens/ix pull request #1287
Opened 2024-05-21 13:33 UTC by matthiashader

## 💡 What is the current behavior?

GitHub Issue Number: #<ISSUE NUMBER>

## 🆕 What is the new behavior?

-
-

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [ ] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [ ] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [ ] 🧐 Static code analysis passes (`pnpm lint`)
- [ ] 🏗️ Successful compilation (`pnpm build`, changes pushed)

## 👨‍💻 Help & support

2024-05-23 12:46 UTC, nuke-ellington submitted a review, later dismissed

2024-06-18 11:28 UTC, danielleroux approved these changes

2024-06-18 11:41 UTC, danielleroux requested changes

2024-06-18 11:41 UTC, danielleroux commented on packages/core/src/components/select/select.tsx
> +
Could be a potential undefined access if no items are provided. Maybe a better place to show this warning will be inside the forEach above.

2024-06-20 07:27 UTC, danielleroux approved these changes

2024-06-20 07:27 UTC, merged