fix(docs/landing-page): Improvements for responsiveness
siemens/ix pull request #1310
Opened 2024-06-05 09:31 UTC by matthiashader

## 💡 What is the current behavior?
- Some sections are breaking on mobile devices
- Overlapping content

GitHub Issue Number: #N/A, [IX-974]

## 🆕 What is the new behavior?

- Section made responsiveness
- improved general sections

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [ ] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [ ] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [ ] 🧐 Static code analysis passes (`pnpm lint`)
- [ ] 🏗️ Successful compilation (`pnpm build`, changes pushed)

## 👨‍💻 Help & support

2024-07-03 11:18 UTC, danielleroux requested changes

2024-07-03 11:18 UTC, danielleroux commented on packages/documentation/src/pages/index.tsx
Why did you change the complete file?

2024-07-08 05:20 UTC, matthiashader commented on packages/documentation/src/pages/index.tsx
Resolved

2024-07-09 07:54 UTC, danielleroux approved these changes

2024-07-19 08:24 UTC, nuke-ellington requested changes
Additionally the icons get jumbled up when resizing.
<img width="1452" alt="Screenshot 2024-07-19 at 10 22 50" src="https://github.com/user-attachments/assets/c7702ea8-ed45-407c-8f7e-91e684e4fd47">

2024-07-19 08:24 UTC, nuke-ellington commented on packages/documentation/src/pages/index.tsx
> -          className={styles.information_cards_background}
Removing the class breaks the styling. Also the corresponding CSS class is not used anywhere else so we should remove it from the stylesheet.

2024-07-19 08:24 UTC, nuke-ellington commented on packages/documentation/src/pages/index.module.scss
> +
```suggestion

```

2024-07-19 08:24 UTC, nuke-ellington commented on packages/documentation/src/pages/index.tsx
> -          className={styles.information_cards_background}
<img width="1243" alt="Screenshot 2024-07-19 at 10 14 23" src="https://github.com/user-attachments/assets/4e9044b4-51b6-4b3b-9882-845afe3581bf">

2024-08-12 11:31 UTC, danielleroux requested changes
Looks broken
![image](https://github.com/user-attachments/assets/517e256f-ddf0-4d1e-9cac-8e12c584eb24)

2024-08-21 07:05 UTC, danielleroux submitted a review, later dismissed

2024-08-21 08:44 UTC, closed without merging