fix(core/scrollbar): fix firefox appearance (scrollbar & input)
siemens/ix pull request #1313
Opened 2024-06-06 10:42 UTC by matthiashader

## 💡 What is the current behavior?
- Input, spefically the pagination has the increment / decrement buttons shown
- Default Scrollbar applied in Firefox

GitHub Issue Number: #N/A

## 🆕 What is the new behavior?

- Increment / Decrement buttons are hidden
- Unfortunately Firefox does not offer that big of a support of scrollbar styling, so only available classes have been used (see https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_scrollbars_styling)
- No Tests since we only test in Chrome

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [ ] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [ ] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [ ] 🧐 Static code analysis passes (`pnpm lint`)
- [ ] 🏗️ Successful compilation (`pnpm build`, changes pushed)

## 👨‍💻 Help & support

2024-06-11 14:33 UTC, nuke-ellington requested changes

2024-06-11 14:33 UTC, nuke-ellington commented on packages/core/src/components/tab-item/tab-item.scss
>        &::after {
Empty selector

2024-06-11 14:33 UTC, nuke-ellington commented on packages/core/src/components/tab-item/tab-item.scss
>      &::after {
Empty selector

2024-06-12 04:29 UTC, matthiashader commented on packages/core/src/components/tab-item/tab-item.scss
>        &::after {
Removed, seems not to be needed

2024-06-12 04:29 UTC, matthiashader commented on packages/core/src/components/tab-item/tab-item.scss
>      &::after {
Removed, seems not to be needed

2024-06-12 08:30 UTC, nuke-ellington approved these changes

2024-06-14 14:13 UTC, danielleroux commented
Closes #1202

2024-06-14 14:13 UTC, merged