Forms overhaul (including several components)
siemens/ix pull request #1318
Opened 2024-06-11 08:05 UTC by danielleroux

## 💡 What is the current behavior?

GitHub Issue Number: #<ISSUE NUMBER>

## 🆕 What is the new behavior?

-
-

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [ ] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [ ] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [ ] 🧐 Static code analysis passes (`pnpm lint`)
- [ ] 🏗️ Successful compilation (`pnpm build`, changes pushed)

## 👨‍💻 Help & support

2024-06-24 13:13 UTC, danielleroux commented
/snapshots:approve --args=form-fields.e2e.ts

2024-06-27 07:02 UTC, danielleroux commented
/release:pr

2024-06-27 07:06 UTC, danielleroux commented
/release:pr

2024-06-27 08:04 UTC, danielleroux commented
/release:pr

2024-07-29 06:24 UTC, danielleroux commented on packages/core/src/components/field-label/field-label.tsx
> +
This should be implemented via Prop because label can be used external, use htmlFor or the controlRef to get the validation state

2024-08-14 14:00 UTC, nuke-ellington requested changes

2024-09-12 11:56 UTC, AndreasBerliner approved these changes

2024-10-09 08:16 UTC, jul-lam requested changes

2024-10-09 08:16 UTC, jul-lam commented on packages/html-test-app/src/preview-examples/form-checkbox-group-indeterminate.css
The form-validation.css is missing in the html-test-app.

2024-10-09 08:20 UTC, jul-lam commented on packages/react-test-app/src/preview-examples/form-checkbox-group-indeterminate.css
> +
The comment regarding the auto generation is missing in this file.

2024-10-09 08:21 UTC, jul-lam commented on packages/html-test-app/src/preview-examples/form-checkbox-group-indeterminate.css
> +
The comment regarding the auto generation is missing in this file.

2024-10-09 08:24 UTC, jul-lam commented on packages/vue-test-app/src/preview-examples/form-checkbox-group-indeterminate.vue
> +<script setup lang="ts">
Newline is missing above the script tag.

2024-10-09 08:26 UTC, jul-lam commented on packages/react-test-app/src/preview-examples/input-legacy-disabled.tsx
> +
To many newlines.

2024-10-09 08:26 UTC, jul-lam commented on packages/react-test-app/src/preview-examples/input-legacy-readonly.tsx
> +
Too many newlines.

2024-10-09 08:27 UTC, jul-lam commented on packages/react-test-app/src/preview-examples/input-legacy.tsx
> +
Too many newlines.

2024-10-09 08:28 UTC, jul-lam commented on packages/react-test-app/src/preview-examples/textarea-legacy-readonly.tsx
> +
Too many newlines

2024-10-09 08:39 UTC, jul-lam requested changes
Really great feature, especially since I already had the chance to test it myself.

2024-10-11 10:03 UTC, jul-lam approved these changes

2024-11-05 10:11 UTC, AndreasBerliner requested changes
TODO: Create Changesets and remove changeset from PR #1540

2024-11-21 11:38 UTC, jul-lam approved these changes

2024-11-21 11:42 UTC, merged