feat(angular): provide angular standalone components
siemens/ix pull request #1325
Opened 2024-06-14 11:44 UTC by danielleroux

## 🆕 What is the new behavior?

Support standalone components in parallel to Module based components

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [ ] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [ ] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [ ] 🧐 Static code analysis passes (`pnpm lint`)
- [ ] 🏗️ Successful compilation (`pnpm build`, changes pushed)

## 👨‍💻 Help & support

2024-07-29 14:31 UTC, nuke-ellington requested changes

2024-07-29 14:31 UTC, nuke-ellington commented on packages/core/src/setup.ts
> + * SPDX-FileCopyrightText: 2023 Siemens AG
```suggestion
 * SPDX-FileCopyrightText: 2024 Siemens AG
```

2024-08-29 10:26 UTC, matthiashader commented on BREAKING_CHANGES.md
> +If you have further questions or you are facing any problems during migration please [contact us over our forum](https://community.siemens.com/c/ix/).
```suggestion
If you have any further questions or you encounter any issues during the migration, please [contact us over our forum](https://community.siemens.com/c/ix/).
```

2024-09-04 07:53 UTC, matthiashader submitted a review, later dismissed

2024-09-04 13:41 UTC, nuke-ellington requested changes

2024-09-04 13:41 UTC, nuke-ellington commented on BREAKING_CHANGES/v3.md
> +Above will fetch the svg from `https://some-resource-domain/star.svg`
```suggestion
Above will fetch the SVG from `https://some-resource-domain/star.svg`
```

2024-09-04 14:08 UTC, nuke-ellington approved these changes

2024-09-04 14:29 UTC, merged