fix(core/dropdown): spacing and color
siemens/ix pull request #1343
Opened 2024-06-20 08:53 UTC by matthiashader

## 💡 What is the current behavior?
- icon color not correct
- text to narrow on the icon

GitHub Issue Number: #N/A, [IX-707]

## 🆕 What is the new behavior?

- Icon has var(--theme-color-std-text) as color
- dropdown-item-text has padding-left: 0.25rem

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [ ] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [ ] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [ ] 🧐 Static code analysis passes (`pnpm lint`)
- [ ] 🏗️ Successful compilation (`pnpm build`, changes pushed)

## 👨‍💻 Help & support

2024-06-21 08:27 UTC, nuke-ellington requested changes

2024-06-21 08:27 UTC, nuke-ellington commented on packages/core/src/components/dropdown-item/dropdown-item.scss
> +    padding-left: 0.25rem;
Why not increase the margin of the icon instead so that the extra space will only get applied if the icon is actually present?

2024-07-03 11:27 UTC, nuke-ellington requested changes
Add test for dropdown item checked

2024-07-04 07:59 UTC, matthiashader commented
> Add test for dropdown item checked

Resolved

2024-07-18 12:46 UTC, nuke-ellington requested changes

2024-07-18 12:46 UTC, nuke-ellington commented on packages/core/src/components/dropdown-item/dropdown-item.tsx
> +  @Event() itemClick?: EventEmitter<HTMLIxDropdownItemElement>;
```suggestion
  @Event() itemClick!: EventEmitter<HTMLIxDropdownItemElement>;
```

2024-07-22 08:46 UTC, nuke-ellington approved these changes

2024-07-29 13:55 UTC, merged