refactor(core): reduce strict errors
siemens/ix pull request #1488
Opened 2024-09-18 14:13 UTC by danielleroux

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [ ] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [ ] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [ ] 🧐 Static code analysis passes (`pnpm lint`)
- [ ] 🏗️ Successful compilation (`pnpm build`, changes pushed)

## 👨‍💻 Help & support

2024-09-26 07:55 UTC, matthiashader submitted a review, later dismissed

2024-09-26 10:20 UTC, nuke-ellington requested changes
Changeset is missing

2024-09-26 11:19 UTC, AndreasBerliner commented on packages/core/src/components/css-grid/css-grid.tsx
> +    if (this.currentTemplate && this.currentTemplate.length !== 0) {
Is there a specific reason why this was changed? I prefer using the optional chaining operator.

2024-09-26 11:58 UTC, nuke-ellington approved these changes

2024-09-30 13:23 UTC, AndreasBerliner approved these changes

2024-10-02 08:12 UTC, merged