fix(core/card-list): adapt title margin to figma
siemens/ix pull request #1492
Opened 2024-09-24 08:44 UTC by matthiashader

## 💡 What is the current behavior?
- -  Margin from header to card-list is 8px -> 0.5rem

GitHub Issue Number: Closes #1491, 

## 🆕 What is the new behavior?

-  Margin from header to card-list is 16px -> 1rem
-

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [ ] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [ ] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [ ] 🧐 Static code analysis passes (`pnpm lint`)
- [ ] 🏗️ Successful compilation (`pnpm build`, changes pushed)

## 👨‍💻 Help & support

2024-09-25 08:42 UTC, danielleroux requested changes
- [x] Reduce `strict` errors

2024-09-25 09:21 UTC, nuke-ellington approved these changes

2024-10-10 09:39 UTC, nuke-ellington approved these changes

2024-10-10 10:21 UTC, danielleroux requested changes

2024-10-10 10:21 UTC, danielleroux commented on packages/core/src/components/card-list/card-list.tsx
> +          label={this.label!}
See sonarcloud report

2024-10-17 10:00 UTC, danielleroux approved these changes

2024-10-22 14:47 UTC, merged