fix(core): improve component a11y
siemens/ix pull request #1497
Opened 2024-09-27 08:50 UTC by nuke-ellington

## 💡 What is the current behavior?

Components provide lighthouse a11y scores of less than 100% because of misused semantic html and aria attributes

GitHub Issue Number: #<ISSUE NUMBER>

## 🆕 What is the new behavior?

- affected components should have 100% a11y scores
-

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [x] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [x] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [x] 🧐 Static code analysis passes (`pnpm lint`)
- [x] 🏗️ Successful compilation (`pnpm build`, changes pushed)

## 👨‍💻 Help & support

2024-10-16 10:32 UTC, matthiashader requested changes
changeset missing

2024-10-17 06:19 UTC, matthiashader requested changes

2024-10-17 06:19 UTC, matthiashader commented on packages/core/src/components/menu/menu.tsx
> +        <nav
Is this change necessary? Should the aside stay and the <div id="menu-tabs" be replaced with nav? (https://www.w3.org/TR/2011/WD-html5-author-20110809/the-aside-element.html, https://stackoverflow.com/questions/40390390/semantic-differences-between-nav-and-aside-for-navigation-in-html)

2024-10-17 06:19 UTC, matthiashader commented on packages/core/src/components/pane/pane.tsx
> +  private readonly collapsedPaneMobile = '48px';
`private static readonly collapsedPaneMobile`

2024-10-17 06:57 UTC, matthiashader commented
Further elements that haven't 100% accessibility score in Lighthouse:
- ix-push-card
- ix-breadcrumb
- ix-icon-toggle-button
- ix-slider

2024-10-17 12:49 UTC, nuke-ellington commented
> changeset missing
> 
> reduce strict errors

Category filter strict errors will be addressed via #1522

2024-10-21 08:48 UTC, matthiashader commented on packages/core/src/components/menu/menu.tsx
> +                    if (this.applicationLayoutContext?.appSwitchConfig) {
Why do we need this query `if (this.applicationLayoutContext?.appSwitchConfig) {`. Shouldn't this be covered with line 610?

2024-10-22 05:43 UTC, matthiashader approved these changes

2024-10-22 08:04 UTC, merged