fix(card): card-filled colors for hover/active states
siemens/ix pull request #1498
Opened 2024-10-01 12:29 UTC by AndreasBerliner

…g to design

## 💡 What is the current behavior?

GitHub Issue Number: #<ISSUE NUMBER>

## 🆕 What is the new behavior?

-
-

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [ ] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [ ] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [ ] 🧐 Static code analysis passes (`pnpm lint`)
- [ ] 🏗️ Successful compilation (`pnpm build`, changes pushed)

## 👨‍💻 Help & support

2024-10-02 07:43 UTC, nuke-ellington requested changes
We should add a VRT for the filled variant

2024-10-10 06:27 UTC, matthiashader commented on packages/core/src/components/card/card.scss
> +:host( .card-outline:active) {
typo whitespace -> :host(.card-outline:active) {

2024-10-10 06:27 UTC, matthiashader commented on packages/core/src/tests/push-card/push-card.e2e.ts-snapshots/push-card-basic-should-not-have-visual-regressions-1-chromium---theme-classic-light-darwin.png
do not include macos vrts?

2024-10-10 06:53 UTC, matthiashader submitted a review, later dismissed

2024-10-16 07:53 UTC, matthiashader submitted a review, later dismissed

2024-10-23 05:26 UTC, matthiashader approved these changes

2024-10-23 07:25 UTC, nuke-ellington approved these changes

2024-10-23 07:27 UTC, merged