feat(core/message): add options to set size and position
siemens/ix pull request #1533
Opened 2024-10-23 13:25 UTC by nuke-ellington

## 💡 What is the current behavior?

GitHub Issue Number: IX-1149

## 🆕 What is the new behavior?

-
-

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [x] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [x] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [x] 🧐 Static code analysis passes (`pnpm lint`)
- [x] 🏗️ Successful compilation (`pnpm build`, changes pushed)

## 👨‍💻 Help & support

2024-10-24 07:44 UTC, danielleroux requested changes

2024-10-24 07:44 UTC, danielleroux commented on packages/core/src/components/utils/modal/message.ts
> +
Type is never used anywhere

2024-10-24 07:44 UTC, danielleroux commented on packages/core/src/components/utils/modal/message.ts
> +  let actions: any[] = [];
no any!

2024-10-25 09:57 UTC, danielleroux requested changes

2024-10-25 09:57 UTC, danielleroux commented on packages/core/src/components/utils/modal/message.ts
> -  | MessageContent;
Why did you removed this type? Its a good idea in general to have a MessageConfig which reflects the ModalConfig

2024-10-25 09:57 UTC, danielleroux commented on packages/core/src/components/utils/modal/message.ts
> +  size?: IxModalSize;
We should export type in the utils/modal/index file

2024-10-28 12:46 UTC, AndreasBerliner commented on packages/core/src/tests/message/mesage.e2e.ts
filename has a typo

2024-11-05 08:58 UTC, danielleroux approved these changes

2024-11-05 08:58 UTC, merged