fix(core/datetime-picker): responsiveness, strict typing, spacing
siemens/ix pull request #1558
Opened 2024-11-11 12:18 UTC by matthiashader

## 💡 What is the current behavior?
- time picker takes not full width on mobile
- spacing is not correct on mobile

GitHub Issue Number: Closes #697, [IX-1614] 

## 🆕 What is the new behavior?

- time picker takes  full width on mobile
- adapted spacing
- bottom margin from the time-picker = 2rem

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [ ] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [ ] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [ ] 🧐 Static code analysis passes (`pnpm lint`)
- [ ] 🏗️ Successful compilation (`pnpm build`, changes pushed)

## 👨‍💻 Help & support

2024-11-19 16:18 UTC, danielleroux requested changes

2024-11-19 16:18 UTC, danielleroux commented on .changeset/twenty-mangos-grin.md
> +fix(core/date-time-picker): responsiveness and spacing, strict typing
```suggestion
Improve responsive behaviour of `ix-datetime-picker` on small screens 
```

2024-11-19 16:18 UTC, danielleroux commented on packages/core/src/components/datetime-picker/datetime-picker.scss
> +  --btn-width: 100%;
What is the idea of using custom css property here? This should not be a setting which a user should customize.

Use should use a scss variable if it used internal.

2024-11-19 16:18 UTC, danielleroux commented on packages/core/src/components/datetime-picker/datetime-picker.scss
> +      position: absolute;
Do we really need a absolute position here? Looks like the data container can also be placed using `relative` position.

2024-11-19 16:18 UTC, danielleroux commented on packages/core/src/components/datetime-picker/datetime-picker.tsx
> +  @Prop() showTimeReference?: boolean;
```suggestion
  @Prop() showTimeReference: boolean = false;
```

2024-11-19 16:18 UTC, danielleroux commented on packages/core/src/components/datetime-picker/datetime-picker.tsx
> +  @Prop() locale?: string = undefined;
```suggestion
  @Prop() locale?: string;
```

2024-11-20 12:59 UTC, nuke-ellington requested changes

2024-11-20 12:59 UTC, nuke-ellington commented on packages/core/src/components/date-picker/date-picker.tsx
Use updated icon imports

2024-11-20 12:59 UTC, nuke-ellington commented on packages/core/src/components/date-dropdown/date-dropdown.scss
> +    margin-top: 1rem;
Why is there a `margin-top` on the button now?

2024-11-20 12:59 UTC, nuke-ellington commented on packages/core/src/tests/textarea/textarea.e2e.ts-snapshots/textarea-basic-1-chromium---theme-classic-dark-linux.png
Why is the text area affected by this PR?

2024-11-21 09:34 UTC, merged