fix(core/tooltip|dropdown): find trigger if in same shadow DOM
siemens/ix pull request #1560
Opened 2024-11-12 10:01 UTC by nuke-ellington

## 💡 What is the current behavior?

GitHub Issue Number: #<ISSUE NUMBER>

## 🆕 What is the new behavior?

-
-

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [x] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [x] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [x] 🧐 Static code analysis passes (`pnpm lint`)
- [x] 🏗️ Successful compilation (`pnpm build`, changes pushed)

## 👨‍💻 Help & support

2024-11-21 09:38 UTC, matthiashader requested changes
changeset missing & strict typing (if its necessary inside an unit test)

2024-11-21 09:53 UTC, jul-lam requested changes

2024-11-21 09:53 UTC, jul-lam commented on packages/core/src/components/utils/find-element.ts
> +  return Promise.resolve(elementsInShadowRoot);
```suggestion
  if (elementsInShadowRoot.length > 0) {
    return Promise.resolve(elementsInShadowRoot);
  }
  
  return Promise.resolve(undefined);
```

2024-11-21 12:18 UTC, matthiashader submitted a review, later dismissed

2024-11-25 10:08 UTC, danielleroux approved these changes

2024-11-25 10:12 UTC, jul-lam approved these changes

2024-11-25 10:12 UTC, merged