fix(core/drawer|inputgroup): fixed drawer display issue
siemens/ix pull request #1561
Opened 2024-11-13 15:55 UTC by ridvandmrc

## 💡 What is the current behavior?
- initial drawer display style is none so that child cannot calculate its width or height.
- because if parent is disable that means that child cannot calculate from DOM

GitHub Issue Number: #1551

## 🆕 What is the new behavior?

- Updated drawer style and refactored input-group

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [X] 🦮 Accessibility (a11y) features were implemented
- [X] 🗺️ Internationalization (i18n) - no hard coded strings
- [X] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [X] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [ ] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [ ] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [ ] 🧐 Static code analysis passes (`pnpm lint`)
- [ ] 🏗️ Successful compilation (`pnpm build`, changes pushed)

## 👨‍💻 Help & support

2024-12-19 08:39 UTC, nuke-ellington requested changes

2024-12-19 14:57 UTC, nuke-ellington reviewed
see comment

2025-01-08 12:03 UTC, nuke-ellington reviewed
TBD when will `ix-input-group` be deprecated/removed?

2025-01-08 12:03 UTC, nuke-ellington commented on packages/core/src/components/input-group/input-group.tsx
> + * @deprecated since 2.6.1. Will be removed with 3.0.0.
```suggestion
 * @deprecated since 3.0.0. Will be removed with 4.0.0.
```

2025-01-10 11:52 UTC, ridvandmrc commented on packages/core/src/components/drawer/drawer.scss
> +  position: fixed;
If we don't use position: fixed, it wil have scroll problem for long page like:
![image](https://github.com/user-attachments/assets/ce3fc3b8-7dae-4933-93a8-9db6354bff6f)

position:absolute, gets **body**  as a reference so, it will have horizontal problem while presenting the drawer (only animation).
![image](https://github.com/user-attachments/assets/3ce137e5-1708-4544-9c03-43d6e8811f0b)

2025-01-10 11:54 UTC, ridvandmrc commented on packages/core/src/components/drawer/drawer.scss
> +  position: fixed;
I am not sure it is really breaking change, because this will not affect user behavior, it does not break anything I guess

2025-01-10 11:56 UTC, ridvandmrc commented on packages/core/src/components/drawer/drawer.scss
> +  position: fixed;
If you think these are not important, we can keep as 'position:absolute'.

2025-01-16 12:03 UTC, matthiashader commented on packages/core/src/components/drawer/drawer.scss
> +  position: fixed;
@ridvandmrc, you still can use the drawer inside a container and place the container accordingly with 'position: absolute', in your example. Additionally i have implemented some test cases that show, that 'position: fixed' will break the behavior. 
But for better understanding, could you provide use with your use case for that - or an working stackblitz example, that explain the desired behavior, or why 'position: fixed' is really necessary?

2025-01-16 12:46 UTC, ridvandmrc commented on packages/core/src/components/drawer/drawer.scss
> +  position: fixed;
Hi @matthiashader ,
you can just check here and see the horizontal scroll while showing after click the button.

https://stackblitz.com/~/edit/xnfrdi-xnh1ycg4?file=src/app/app.component.html

in here example from material UI, 
https://mui.com/material-ui/react-drawer/

for any case, if this way is fine for you, you can resolve this conversation

2025-01-20 08:59 UTC, matthiashader commented on packages/core/src/components/drawer/drawer.scss
> +  position: fixed;
@ridvandmrc - i got you now, but sitll you can prevent the overflow in the parent container. 
https://stackblitz.com/edit/crrd56xp?file=src%2Findex.html

However, in the next commit(s) I tried to adapt the behaviour accordingly, i.e. the animation is not done by moving the drawer but by adjusting the width, keeping your requirement in mind!

2025-01-30 15:03 UTC, nuke-ellington requested changes

2025-01-30 15:03 UTC, nuke-ellington commented on packages/core/src/components/drawer/drawer.tsx
> +        el.style.opacity = '0';
Why is this part of `begin`? This will vanish the content before animation is completed. It also causes the height of the drawer to jump to ~0 when not in full height mode.

2025-02-13 15:23 UTC, nuke-ellington commented on packages/core/src/components/drawer/drawer.tsx
> +          {' '}
```suggestion
```

2025-02-24 10:31 UTC, nuke-ellington requested changes

2025-02-24 10:31 UTC, nuke-ellington commented on packages/core/src/components/drawer/drawer.tsx
> +    console.log('show changed', newValue, oldValue);
```suggestion
```

2025-02-24 10:31 UTC, nuke-ellington commented on packages/core/src/components/drawer/drawer.tsx
> +        if (this.divElement) {
This conditional pushes the cognitive complexity above 15 (compare Sonarqube). The null check is performed in the fn, too. Is this really necessary?

2025-02-24 10:31 UTC, nuke-ellington commented on packages/core/src/components/drawer/drawer.tsx
> +        if (this.divElement) {
Same as above.

2025-02-24 12:35 UTC, nuke-ellington approved these changes

2025-02-24 13:04 UTC, matthiashader approved these changes

2025-02-25 11:59 UTC, nuke-ellington approved these changes

2025-02-28 10:06 UTC, nuke-ellington approved these changes

2025-02-28 10:15 UTC, merged