feat(core/categroy-filter): add filter cleared event
siemens/ix pull request #1562
Opened 2024-11-14 10:18 UTC by nuke-ellington

## 💡 What is the current behavior?

GitHub Issue Number: #<ISSUE NUMBER>

## 🆕 What is the new behavior?

-
-

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [x] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [x] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [x] 🧐 Static code analysis passes (`pnpm lint`)
- [x] 🏗️ Successful compilation (`pnpm build`, changes pushed)

## 👨‍💻 Help & support

2024-11-20 09:11 UTC, jul-lam approved these changes

2024-11-21 12:23 UTC, danielleroux requested changes
- strict error
- changeset missing

2024-11-22 12:00 UTC, danielleroux requested changes

2024-11-22 12:00 UTC, danielleroux commented on .changeset/large-cherries-attend.md
> +"@siemens/ix-vue": patch
```suggestion
"@siemens/ix-angular": minor
"@siemens/ix": minor
"@siemens/ix-vue": minor
```

2024-11-25 10:07 UTC, danielleroux approved these changes

2024-11-25 10:07 UTC, merged