fix(core/ix-pane-layout): provide close/open event and default slot
siemens/ix pull request #1563
Opened 2024-11-14 13:53 UTC by matthiashader

## 💡 What is the current behavior?

GitHub Issue Number: #<ISSUE NUMBER>

## 🆕 What is the new behavior?

-
-

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [ ] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [ ] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [ ] 🧐 Static code analysis passes (`pnpm lint`)
- [ ] 🏗️ Successful compilation (`pnpm build`, changes pushed)

## 👨‍💻 Help & support

2024-11-18 08:31 UTC, nuke-ellington requested changes
Why not provide dedicated expand and collapse events?

2024-11-18 08:31 UTC, nuke-ellington commented on .changeset/seven-coins-fly.md
> +'@siemens/ix-vue': patch
```suggestion
'@siemens/ix-angular': minor
'@siemens/ix': minor
'@siemens/ix-vue': minor
```

2024-11-20 09:16 UTC, jul-lam requested changes

2024-11-20 09:16 UTC, jul-lam commented on .changeset/seven-coins-fly.md
> +feat(core/pane-layout): provide close/open event and default slot #1563
Adapt changeset to new format

2024-11-20 15:26 UTC, nuke-ellington commented on .changeset/seven-coins-fly.md
> +Update expandedChange event to trigger only on user interactions and refine default slot behavior in ix-pane-layout.
```suggestion
Update expandedChange event to trigger only on user interactions and add unnamed default slot for ix-pane-layout content.
```

2024-11-21 09:30 UTC, merged