Introduce storybook into development process
siemens/ix pull request #1564
Opened 2024-11-18 09:52 UTC by danielleroux

## 🆕 What is the new behavior?

Introduce storybook

(/cc #1130)

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [ ] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [ ] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [ ] 🧐 Static code analysis passes (`pnpm lint`)
- [x] 🏗️ Successful compilation (`pnpm build`, changes pushed)

## 👨‍💻 Help & support

2024-11-19 08:04 UTC, jul-lam requested changes

2024-11-19 08:04 UTC, jul-lam commented on packages/storybook-docs/src/stories/Button.stories.ts
Filename sollte lower case sein.

2024-11-19 08:04 UTC, jul-lam commented on packages/storybook-docs/src/stories/Modal.stories.ts
Filename sollte lower case sein.

2024-11-19 08:04 UTC, jul-lam commented on packages/core/package.json
>      "test:spec": "stencil test --spec",
test scipts sollten auch auf "." geändert werden.

2024-11-21 09:25 UTC, matthiashader commented on packages/storybook-docs/.storybook/preview.ts
> +    //   });
has been removed, as a plugin takes care of it

2024-11-21 09:56 UTC, jul-lam submitted a review, later dismissed

2024-11-21 09:58 UTC, matthiashader submitted a review, later dismissed

2024-11-21 12:20 UTC, merged