fix(core/toggle): link label and input field to be clickable
siemens/ix pull request #1587
Opened 2024-11-29 09:53 UTC by danielleroux

## 💡 What is the current behavior?

GitHub Issue Number: closes #1585

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [ ] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [ ] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [ ] 🧐 Static code analysis passes (`pnpm lint`)
- [x] 🏗️ Successful compilation (`pnpm build`, changes pushed)

## 👨‍💻 Help & support

2024-11-29 13:08 UTC, nuke-ellington reviewed
Label is not clickable anymore. Was that on purpose? Still shows the pointer cursor.

2024-12-09 12:43 UTC, AndreasBerliner submitted a review, later dismissed

2024-12-09 13:13 UTC, nuke-ellington requested changes

2024-12-09 13:13 UTC, nuke-ellington commented on .changeset/thin-frogs-relax.md
> +Make **ix-toggle** clickable if disable property is present (Fixes #1585)
```suggestion
Make **ix-toggle** not clickable if disabled property is present (Fixes #1585)
```

2024-12-09 13:13 UTC, nuke-ellington commented on packages/core/src/components/toggle/toggle.scss
> +  .wrapper {
Whole clickable area should have `cursor: pointer` while not `disabled`.

2024-12-10 10:29 UTC, nuke-ellington approved these changes

2024-12-12 10:24 UTC, AndreasBerliner approved these changes

2024-12-12 10:39 UTC, nuke-ellington approved these changes

2024-12-16 09:55 UTC, merged