fix(core/select): replace element ref with make-ref function
siemens/ix pull request #1595
Opened 2024-12-03 16:35 UTC by danielleroux

## 💡 What is the current behavior?

GitHub Issue Number: Closes #1594

## 🆕 What is the new behavior?

- Fix issue were controlRef is used with a native element instead of MakeRef

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [ ] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [ ] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [ ] 🧐 Static code analysis passes (`pnpm lint`)
- [x] 🏗️ Successful compilation (`pnpm build`, changes pushed)

## 👨‍💻 Help & support

2024-12-04 08:56 UTC, nuke-ellington requested changes

2024-12-04 08:56 UTC, nuke-ellington commented on packages/core/src/components/utils/make-ref.ts
> +export function isMakeRef<T>(obj: unknown): obj is MakeRef<T> {
Unused code?

2024-12-05 09:07 UTC, danielleroux commented on packages/core/src/components/utils/make-ref.ts
> +export function isMakeRef<T>(obj: unknown): obj is MakeRef<T> {
Removed

2024-12-06 10:50 UTC, nuke-ellington approved these changes

2024-12-06 10:52 UTC, merged