V3 icon docs
siemens/ix pull request #1600
Opened 2024-12-05 13:50 UTC by nuke-ellington

## 💡 What is the current behavior?

GitHub Issue Number: IX-1587

## 🆕 What is the new behavior?

-
-

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [x] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [ ] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [ ] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [ ] 🧐 Static code analysis passes (`pnpm lint`)
- [ ] 🏗️ Successful compilation (`pnpm build`, changes pushed)

## 👨‍💻 Help & support

2025-01-13 10:26 UTC, matthiashader requested changes

2025-01-13 10:26 UTC, matthiashader commented on packages/documentation/docs/icon-library/_icon_code.md
> +Therefor icons need to be imported explicitly.
```suggestion
Only the icons actually used in the application will be part of the bundle to save bandwidth and memory.
As a result, icons must now be imported explicitly.
```

2025-01-13 10:27 UTC, matthiashader commented on packages/documentation/src/components/ThemeShadows/index.tsx
Where does the requirement for these changes come from?

2025-01-13 10:27 UTC, matthiashader reviewed
changeset missing

2025-01-13 15:34 UTC, nuke-ellington commented on packages/documentation/src/components/ThemeShadows/index.tsx
Wanted to get rid of the search for a long time and felt the itch to do it. It just does not make sense to filter, when there are only five items available.

2025-01-15 13:26 UTC, matthiashader submitted a review, later dismissed

2025-01-28 06:40 UTC, danielleroux requested changes
- Missing component tests 
- Preview examples implemented only for angular, what happens with the other preview examples (react, vue)?
-

2025-01-28 06:40 UTC, danielleroux commented on BREAKING_CHANGES/v3.md
> +Then you can reference the loaded iX icons by name anywhere in your application.
Why do we need this functionality?

2025-01-28 06:40 UTC, danielleroux commented on packages/documentation/docs/icon-library/_icon_code.md
> +```
Same as in BREAKING_CHANGES.md

2025-01-28 06:40 UTC, danielleroux commented on packages/documentation/docs/icon-library/_icon_code.md
> +<IxIcon name="{iconStar}" size="32"></IxIcon>
Variable assignment syntax is wrong here

2025-01-28 06:40 UTC, danielleroux commented on packages/documentation/docs/icon-library/_icon_code.md
> +<IxIcon name="{iconStar}" size="32"></IxIcon>
Variable assignment syntax is wrong here

2025-02-13 14:00 UTC, jul-lam requested changes

2025-02-13 14:00 UTC, jul-lam commented on packages/angular-test-app/src/main.ts
> +
```suggestion
```

2025-02-13 14:00 UTC, jul-lam commented on packages/angular-test-app/src/preview-examples/add-icons.ts
> +  }
In the standalone example we did this in the constructor - we should make it consistent.

2025-02-13 14:00 UTC, jul-lam commented on packages/documentation/src/components/Icons.tsx
> +              onClick={() => {}}
Should we copy the icon name on click?

2025-02-13 14:00 UTC, jul-lam commented on packages/react-test-app/src/preview-examples/add-icons.tsx
The examples are not consistent across different frameworks.

2025-02-14 10:09 UTC, danielleroux commented on packages/documentation/src/components/Icons.tsx
> +              onClick={() => {}}
Will be handled by a different PR

2025-02-19 08:52 UTC, jul-lam approved these changes

2025-02-20 12:16 UTC, merged