docs: intro sentence for date-dropdown
siemens/ix pull request #1605
Opened 2024-12-06 13:33 UTC by flxlst09

## 💡 What is the current behavior?

no intro sentence for date dropdown

## 🆕 What is the new behavior?

new intro sentence for date dropdown

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [ ] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [ ] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [ ] 🧐 Static code analysis passes (`pnpm lint`)
- [ ] 🏗️ Successful compilation (`pnpm build`, changes pushed)

## 👨‍💻 Help & support

2024-12-13 12:12 UTC, tokyojen commented on packages/documentation/docs/controls/buttons/link-button.md
> +Link buttons lead users to another location within the application or outside of it and  contain a chevron and a text label.
```suggestion
Link buttons take users to another location either within or outside the application and contain a chevron and a text label.
```

2024-12-13 12:40 UTC, tokyojen commented on packages/documentation/docs/controls/buttons/toggle-buttons.md
> +Toggle buttons allow users to activate and deactivate a function.
```suggestion
Toggle buttons allow users to either activate or deactivate a function.
```

2024-12-13 13:01 UTC, tokyojen commented on packages/documentation/docs/controls/buttons/dropdown-button.md
> +Dropdown buttons reveal a list of actions on click on a button.
```suggestion
Dropdown buttons reveal a list of actions when selected.
```

2024-12-13 13:10 UTC, tokyojen commented on packages/documentation/docs/controls/application-frame/application-header.md
> +Application headers provide a structured area for key elements like the brand logo, application name, and user avatar.
```suggestion
Application headers provide a structured area for key elements like brand logo, application name and user avatar.
```

2024-12-13 13:14 UTC, tokyojen commented on packages/documentation/docs/controls/application-frame/about-and-legal.md
> +The about and legal overlay displays application information, versions, license terms, and other legal content.
```suggestion
The about and legal overlay displays application information, versions, license terms and other legal content.
```

2024-12-13 13:17 UTC, tokyojen commented on packages/documentation/docs/controls/application-frame/popover-news.md
> +Popover news present important updates and information when the application starts.
```suggestion
Popover news presents important updates and information when the application starts.
```

2024-12-16 10:54 UTC, tokyojen commented on packages/documentation/docs/controls/_category-filter_styleguide.md
> +The category filter component enhances data navigation and user experience. We typically use a category filter to efficiently navigate large data sets, being particularly useful in scenarios with com
```suggestion
The category filter component enhances data navigation and user experience. We typically use a category filter to efficiently navigate large data sets, and it's particularly useful for complex data scenarios. The filter also enhances the user experience by providing autocomplete suggestions and customizable filter conditions.
```

2024-12-16 11:01 UTC, tokyojen commented on packages/documentation/docs/controls/_content-header_styleguide.md
> +The content header helps our users understand what the page is about. We typically use it at the very top of the page to show a clear hierarchy of the page.
```suggestion
The content header helps users understand what the page is about. We typically use it at the very top of the page to show a clear page hierarchy.
```

2024-12-16 11:06 UTC, tokyojen commented on packages/documentation/docs/controls/custom-field.mdx
> +Custom fields are wrapper components that can host any forms component.
```suggestion
Custom fields are wrapper components that can host any form component.
```

2024-12-16 11:08 UTC, tokyojen commented on packages/documentation/docs/controls/_custom-field_styleguide.mdx
> +The custom field's properties allow you to control the validation state of the field and the helper text. The custom field is a versatile tool to create your own form fields, that can be used in comb
```suggestion
The custom field's properties allow you to control the validation state of the field and the helper text. It's a versatile tool to create your own form fields that can be used in combination with the 'Form' components to create complex forms.
```

2024-12-16 11:16 UTC, tokyojen commented on packages/documentation/docs/controls/_dropdown_styleguide.md
> +We typically use dropdowns to allow users to select one option from a list. Selecting one of the items in the dropdown performs the action.
```suggestion
Dropdown containers allow users to select one option from a list. Selecting one of the items in the dropdown performs the action. 
```

2024-12-16 11:19 UTC, tokyojen commented on packages/documentation/docs/controls/_number-input_styleguide.mdx
> +The number input component is commonly used in forms, calculators, and other areas where precise numerical input is required. We typically use the number input component to ensure accurate and effici
```suggestion
The number input component is commonly used in forms, calculators and other areas where precise numerical input is required. We typically use the number input component to ensure accurate and efficient data entry.
```

2024-12-16 11:24 UTC, tokyojen commented on packages/documentation/docs/controls/_pill_styleguide.md
> +Typically, pills contain a concise label and sometimes an icon. They are not clickable or closable, making them ideal for presenting static information succinctly within an application.
```suggestion
Pills typically contain a concise label and sometimes an icon. They are not clickable or closable, making them ideal for presenting static information succinctly within an application.
```

2024-12-16 12:17 UTC, tokyojen commented on packages/documentation/docs/controls/buttons/_toggle-button_styleguide.md
> +Toggle buttons with and without text labels are available. We typically use toggle buttons within button groups when users can chose between more than two options or when two available options don't
```suggestion
Toggle buttons with and without text labels are available. We typically use toggle buttons within button groups when users can choose between more than two options or when two available options don't follow the on/off metaphor.
```

2024-12-16 12:29 UTC, tokyojen commented on packages/documentation/docs/controls/checkbox.mdx
> +Checkboxes are form controls that allow users to select no, one or more options.
```suggestion
Checkboxes are form controls that allow users to select none, one or more options.
```

2024-12-16 12:29 UTC, tokyojen commented on packages/documentation/docs/controls/drawer.md
> +Drawers are containers that open on click on a button to show additional content.
```suggestion
Drawers are containers that open on the click of a button to show additional content.
```

2024-12-16 12:31 UTC, tokyojen commented on packages/documentation/docs/controls/event-list.md
> +Event lists display a list of any type of elements with additional details.
```suggestion
Event lists display a list of any type of element with additional details.
```

2024-12-16 12:33 UTC, tokyojen commented on packages/documentation/docs/controls/expanding-search.md
> +Expanding searches are search fields that expand on click to save space.
```suggestion
Expanding searches are search fields that expand when clicked to save space.
```

2024-12-16 12:35 UTC, tokyojen commented on packages/documentation/docs/controls/flip.md
> +Flips are containers that flip on click to reveal additional content.
```suggestion
Flips are containers that flip when clicked to reveal additional content.
```

2024-12-16 12:51 UTC, tokyojen commented on packages/documentation/docs/controls/messagebar.md
> +Message bars display important information to users, e.g. feedback, warnings, or errors.
```suggestion
Message bars display important information to users, e.g. feedback, warnings or errors.
```

2024-12-16 12:58 UTC, tokyojen commented on packages/documentation/docs/controls/pagination.md
> +Paginations allow users to navigate between pages of content when it is split for performance reasons.
```suggestion
Paginations allow users to navigate between pages of content when it's split for performance reasons.
```

2024-12-16 13:02 UTC, tokyojen commented on packages/documentation/docs/controls/spinner.md
> +Spinners indicate that a process is running, to provide feedback to the user.
```suggestion
Spinners indicate that a process is running to provide feedback to the user.
```

2024-12-16 13:05 UTC, tokyojen commented on packages/documentation/docs/controls/tooltip.md
> +Tooltips provide additional information when users hover over or focus an element.
```suggestion
Tooltips provide additional information when users hover over or focus on an element.
```

2024-12-16 13:07 UTC, tokyojen commented on packages/documentation/docs/controls/upload.md
> +Uploads allow users to select and upload files from their device by drag-and-drop.
```suggestion
Uploads allow users to select and upload files from their device via drag-and-drop.
```

2024-12-16 13:15 UTC, tokyojen commented on packages/documentation/docs/controls/modal.md
> +Modals present information prominently and are useful to gather essential user input without navigating to another page.
```suggestion
Modals present information prominently and are useful for gathering essential user input without navigating to another page.
```

2024-12-16 13:22 UTC, tokyojen commented on packages/documentation/docs/controls/_forms-checkbox_styleguide.md
> +Checkboxes are commonly used when there are multiple options that can be selected or to easily enable or disable a setting. They are often utilized in forms where users can choose multiple options, s
```suggestion
Checkboxes are commonly used when there are multiple options that can be selected or used to easily enable or disable a setting. They are often utilized in forms where users can choose multiple options, such as selecting items or categories that apply to a specific product or service.
```

2024-12-16 13:23 UTC, tokyojen commented on packages/documentation/docs/controls/_textarea-field_styleguide.mdx
> +The textarea component is typically used in scenarios such as feedback forms, comment sections, and message composition. Its ability to handle extensive text input makes it a versatile tool for colle
```suggestion
The textarea component is typically used in scenarios such as feedback forms, comment sections and message composition. Its ability to handle extensive text input makes it a versatile tool for collecting detailed user information.
```

2024-12-16 13:28 UTC, tokyojen commented on packages/documentation/docs/controls/charts/line-chart.md
> +Advanced line charts are an enhanced version of basic line charts, designed to provide deeper insights and more detailed analysis of data trends. These charts often incorporate features such as multi
```suggestion
Advanced line charts are an enhanced version of basic line charts, designed to provide deeper insights and more detailed analysis of data trends. These charts often incorporate features such as multiple data series, interactive elements and additional annotations to highlight key points or events. Advanced line charts can also include trend lines, moving averages and other statistical tools to help identify patterns and correlations.
```

2024-12-16 13:29 UTC, tokyojen commented on packages/documentation/docs/controls/charts/line-chart.md
> +Basic line charts use a series of data points connected by straight lines to show changes in values, making it easy to identify patterns, trends, and fluctuations. They are particularly effective for
```suggestion
Basic line charts use a series of data points connected by straight lines to show changes in values, making it easy to identify patterns, trends and fluctuations. They are particularly effective for displaying continuous data, such as stock prices, temperature changes or sales figures. Their simplicity and clarity make them a popular choice for dashboards where understanding data trends is essential.
```

2024-12-16 13:48 UTC, tokyojen commented on packages/documentation/docs/controls/application-frame/map-navigation.md
> +Map navigation structures layout to present map-like content, supported by a collapsible context panel and temporary overlays.
```suggestion
Map navigation layout structures present map-like content, supported by a collapsible context panel and temporary overlays.
```

2024-12-16 13:49 UTC, tokyojen commented on packages/documentation/docs/controls/charts/gauge-chart.md
> +Progress arc charts, also known as semi-circular progress bars, are a dynamic way to visualize data and track progress. Unlike (full) circle charts, progress arc charts use a semi-circle or arc to re
```suggestion
Progress arc charts, also known as semi-circular progress bars, are a dynamic way to visualize data and track progress. Unlike full circle charts, progress arc charts use a semi-circle or arc to represent the percentage of completion. This design can be particularly effective in dashboards and user interfaces where space is limited, yet a clear and engaging visual representation is needed. 
```

2024-12-16 13:51 UTC, tokyojen commented on packages/documentation/docs/controls/charts/gauge-chart.md
> +Gauge charts display information as a reading on a dial. They are particularly effective for showing progress towards a goal, performance metrics, or any data that falls within a range.
```suggestion
Gauge charts display information as a reading on a dial. They are particularly effective for showing progress towards a goal, performance metrics or any data that falls within a range.
```

2024-12-16 13:57 UTC, tokyojen commented on packages/documentation/docs/controls/kpi.md
> +KPIs display measured values together with a status to help the user make better decisions.
```suggestion
KPIs display measured values together with a status indicator to help users interpret data.
```

2024-12-16 14:00 UTC, tokyojen commented on packages/documentation/docs/controls/charts/special-chart.md
> +ECharts offers a wide variety of different chart types and features, including interacting with charts that users need in some use cases.
```suggestion
ECharts offers a wide variety of different chart types and features for enhanced visualization and charting. 
```

2024-12-16 15:13 UTC, tokyojen requested changes
Get in touch if you want to discuss any of the changes.

2025-02-18 12:02 UTC, danielleroux commented
Already merged into `docs/redesign-v2`. I close this one here to cleanup some draft pull requrests

2025-02-18 12:02 UTC, closed without merging