fix(core): checkbox changes to match design
siemens/ix pull request #187
Opened 2022-11-25 17:12 UTC by goncalosard

## Summary

Fix #176 

Changed the sizes to match zeplin design.
Please check if this was the intended result.

## How did you test this change?

Tested locally.

2022-11-28 05:49 UTC, danielleroux requested changes

2022-11-28 05:49 UTC, danielleroux commented on packages/core/scss/components/_checkboxes.scss
> +    width: 18px;
@goncalosard same as with radiobutton we check that the `$size` variable should be updated instead of the inline px value

2022-11-28 14:28 UTC, danielleroux requested changes
@goncalosard `Indeterminate` state looks wrong

<img width="174" alt="image" src="https://user-images.githubusercontent.com/2144313/204302619-16ea5ed2-8bb2-40ed-a951-e7e3b91e4a5f.png">

We should also a visual-regression test for it.

2022-11-29 06:00 UTC, danielleroux approved these changes
lgtm

2022-11-29 10:40 UTC, nuke-ellington approved these changes

2022-11-29 11:10 UTC, merged