Feature/button dropdown
siemens/ix pull request #229
Opened 2022-12-07 17:20 UTC by goncalosard

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [ ] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bug fix
- [x] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the new behavior?

Implemented new component dropdown-button as requested in #173 

![image](https://user-images.githubusercontent.com/63813420/206245312-e6446ea7-fb23-41f3-b4b9-e374b99cec94.png)

A new prop in icon-button was also implemented to let the small triangle to be toggle when its used on a dropdown-button.

Build is not passing because of the problem that i'm Windows, so the file component-doc.json needs to be re-commited by someone with mac.

Visual-regression tests for this new component are created, but it is needed to check if any onther tests are failing and the new 
 snapshots need to be commited.

## Code used for testing

        <ix-dropdown-button
          label="Dropdown"
          variant="Primary"
          icon="checkboxes"
        ></ix-dropdown-button>
        <ix-dropdown-button
          label="Dropdown"
          variant="Primary"
          outline
          icon="checkboxes"
        ></ix-dropdown-button>
        <ix-dropdown-button
          label="Dropdown"
          variant="Primary"
          ghost
          icon="checkboxes"
        ></ix-dropdown-button>
        <ix-dropdown-button
          label="Dropdown"
          variant="Primary"
          disabled
          icon="checkboxes"
        ></ix-dropdown-button>
        <ix-dropdown-button
          label=""
          variant="Primary"
          icon="checkboxes"
        ></ix-dropdown-button>
        <ix-dropdown-button
          label=""
          variant="Primary"
          outline
          icon="checkboxes"
        ></ix-dropdown-button>
        <ix-dropdown-button
          label=""
          variant="Primary"
          ghost
          icon="checkboxes"
        ></ix-dropdown-button>
        <ix-dropdown-button
          label=""
          variant="Primary"
          disabled
          icon="checkboxes"
        ></ix-dropdown-button>

## Testing

Tested locally

2022-12-12 06:18 UTC, danielleroux requested changes
- documentation is missing
- angular examples are missing
- react examples are missing
- http examples are missing

2022-12-12 07:56 UTC, danielleroux requested changes

2022-12-12 07:56 UTC, danielleroux commented on packages/core/src/components/dropdown-button/dropdown-button.scss
> +.hide {
add :host selector around class

2022-12-12 07:56 UTC, danielleroux commented on packages/core/src/components/icon-button/icon-button.tsx
> +
We should not add the `dropdown-triangle` as feature flag to icon button.

Please implement the dropdown icon in dropdown button itself.

2022-12-12 10:06 UTC, danielleroux requested changes
- DropdownButton should also provide a possiblity to open a dropdown e.g.

```
<ix-dropdown-button>
  <ix-dropdown-item></ix-dropdown-item>
  <ix-dropdown-item></ix-dropdown-item>
  ....
</ix-dropdown-button>
```

See ix-select

2022-12-14 17:18 UTC, goncalosard commented
@danielleroux 
Last commit fixed the requests you made(css, triangle, dropdown). Added documentation and examples. 
Triangle color is not correct, it cannot inherit, so a variable is needed to match the colors of the icons with the triangle.

2022-12-19 06:14 UTC, danielleroux commented
@goncalosard 

- Please merge with latest main the branch looks stale to me
- After merge with latest you must adapt the documentation regarding the playground component (see other docs e.g. buttons.md)
- Dropdown without icon looks broken
<img width="175" alt="image" src="https://user-images.githubusercontent.com/2144313/208359897-de4af5f3-524e-4384-98a9-389b67efc621.png">

2022-12-19 16:16 UTC, goncalosard commented
> @goncalosard
> 
> * Please merge with latest main the branch looks stale to me
> * After merge with latest you must adapt the documentation regarding the playground component (see other docs e.g. buttons.md)
> * Dropdown without icon looks broken
> 
> <img alt="image" width="175" src="https://user-images.githubusercontent.com/2144313/208359897-de4af5f3-524e-4384-98a9-389b67efc621.png">

@danielleroux 

Added all the requests you made. Please check if its ok.

Build failed because component-doc.json, add your file.

2023-01-11 09:41 UTC, danielleroux approved these changes
lgtm

2023-01-11 09:48 UTC, nuke-ellington approved these changes
lgtm

2023-01-11 11:09 UTC, merged