fix(core): pill alignment
siemens/ix pull request #255
Opened 2022-12-16 12:16 UTC by goncalosard

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [ ] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [x] Bug fix
- [ ] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: #243 

![image](https://user-images.githubusercontent.com/63813420/208095410-bd6728d1-ad1e-4a6f-bb88-5c892fd215db.png)

## What is the new behavior?

Pills with icon and without icon now have the same height.
![image](https://user-images.githubusercontent.com/63813420/208095813-ccaac01a-32d0-4e51-837a-e984713fb308.png)

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Testing

Tested Locally

## Other information

2022-12-19 06:24 UTC, danielleroux requested changes

2022-12-19 06:24 UTC, danielleroux commented on packages/core/src/components/pill/pill.scss
> +  display: flex;
We cant remove inline-prefix here (https://www.w3schools.com/css/css_inline-block.asp), because this cause a line-break.

2022-12-19 16:35 UTC, goncalosard commented
@danielleroux Fixed, please review.

2023-01-10 09:14 UTC, danielleroux commented
@goncalosard Why are there so many file changes?

2023-01-13 09:18 UTC, nuke-ellington approved these changes
lgtm

2023-01-13 09:42 UTC, danielleroux approved these changes
lgtm

2023-01-13 09:43 UTC, merged