fix(core): chip alignment
siemens/ix pull request #259
Opened 2022-12-16 16:45 UTC by goncalosard

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [ ] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [x] Bug fix
- [ ] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

![image](https://user-images.githubusercontent.com/63813420/208147385-284e14db-d822-4ac3-ac49-caa5d9f241d6.png)

Chips with icon have diferent Y than chips with no icon.

## What is the new behavior?

![image](https://user-images.githubusercontent.com/63813420/208146783-17c6b6ce-f487-4e40-9b64-3722c7c0c751.png)

- chip with icon and chip without icon now get the same Y

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Testing

Tested locally

## Other information

2022-12-19 06:27 UTC, danielleroux requested changes

2022-12-19 06:27 UTC, danielleroux commented on packages/core/src/components/chip/chip.scss
> +  display: flex;
Same problem as in #255 we can not remove inline here.

2022-12-19 16:51 UTC, goncalosard commented
@danielleroux  Fixed, please review.

2023-01-10 09:18 UTC, danielleroux commented on packages/core/src/components/chip/chip.scss
> +    margin-right: 0 !important;
Is `!important` here necessary?

2023-01-13 09:18 UTC, nuke-ellington approved these changes
lgtm

2023-01-13 09:43 UTC, danielleroux approved these changes
lgtm

2023-01-13 09:44 UTC, merged