docs(button): update button description
siemens/ix pull request #447
Opened 2023-03-15 14:12 UTC by linstedt

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [ ] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bug fix
- [ ] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: N/A

## What is the new behavior?

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Testing

## Other information

Open Questions:
- Icon button with icon size 32px available in components but not in Styleguide - do we need this variant?
- Icon button shapes: Currently, some components don't follow the rules described here (e.g. clear button in search field) - should it be fixed?
- Button group: What button variants are available? Is there always at least one primary button? Or is that the selected one?

2023-03-16 08:21 UTC, linstedt commented
@danielleroux @nuke-ellington We would like to add a code example on the top to give an interactive example for each description. Silvio had some feedback coming in about the lack of theming of the illustrations, this could be a small work around. What do you think?

2023-03-21 06:41 UTC, danielleroux approved these changes

2023-03-21 15:24 UTC, nuke-ellington requested changes
Made some suggestions to the text

2023-03-21 15:24 UTC, nuke-ellington commented on packages/documentation/docs/controls/_button_styleguide.md
> +| Icon and text | Use if an icon is wanted and the icon metapher might not be known to the user.                                       |
Typo -> metaphor (also following lines)

2023-03-21 15:24 UTC, nuke-ellington commented on packages/documentation/docs/controls/_button_styleguide.md
> +The selected state is only available for tertiary (ghost) grey buttons to visualize an on/off state. Hover and active state are available for the selected variant. The selectable button is commonly u
typo: within

2023-03-21 15:24 UTC, nuke-ellington commented on packages/documentation/docs/controls/_button_styleguide.md
> +A Button group, also known as segmented buttons or toggle buttons, is an element consisting of two or more adjacent buttons. Selection/activation of the buttons can either be mutually exclusive (sing
A button group (lowercase b)?

2023-03-21 15:24 UTC, nuke-ellington commented on packages/documentation/docs/controls/_button_styleguide.md
> +Button can be triggered by clicking/ pressing anywhere within the button container. When the button is focused, it can be triggered by pressing <kbd>Space</kbd>.
A button/Buttons

2023-03-21 15:24 UTC, nuke-ellington commented on packages/documentation/docs/controls/_button_styleguide.md
> +Button labels are not truncated. All text on buttons is 1-line only. Labels should be kept concise to allow users to quickly scan, understand and remember them.
one line only

2023-03-21 15:24 UTC, nuke-ellington commented on packages/documentation/docs/controls/_button_styleguide.md
> +| Hover           | The hover state is indicated by fill color change and text/ icon color change (except primary button).                         |
text/icon (no space after slash, also following columns)

2023-03-21 15:24 UTC, nuke-ellington commented on packages/documentation/docs/controls/_button_styleguide.md
> +| Active          | The active state is indicated by fill color changeand text/ icon color change (except primary button). Equal to pressed state. |
changeand -> change and

2023-03-21 15:24 UTC, nuke-ellington commented on packages/documentation/docs/controls/_button_styleguide.md
> +| Disabled        | The disblabed state is indicated by fill color change and text/ icon color change (except primary button).                     |
disbladed -> disabled

2023-03-21 15:24 UTC, nuke-ellington commented on packages/documentation/docs/controls/_button_styleguide.md
> +- All Buttons have a fix height.
fixed height (also next line)

2023-03-21 15:24 UTC, nuke-ellington commented on packages/documentation/docs/controls/_button_styleguide.md
> +- Avoid generic button labels (e.g. Yes/ No), use meaningful labels instead (e.g. Save, Download, Edit) so that the user easily understands which action is triggered by pressing the button.
Yes/No

2023-03-21 21:00 UTC, linstedt commented on packages/documentation/docs/controls/_button_styleguide.md
I totally agree, lower case is fine. It is just an artifact from reusing Common Style snippets. All comments should be resolved with the lastest commit. Thanks for the thorough check!

2023-03-21 21:04 UTC, linstedt commented on packages/documentation/docs/controls/_button_styleguide.md
> +| Selected        | The selected state is indicated by text/ icon and fill color change. Only available for tertiary (ghost) grey button.          |
I haven't changed anything here. From my understanding, all variants can be used for selected buttons (text-only, icon-only, text and icon) just like above. I stuck to the same wording not to be confusing the reader. Did I miss something here?

2023-03-22 08:19 UTC, nuke-ellington approved these changes
lgtm

2023-03-22 09:47 UTC, merged