fix(core/group): group selected style and actions & header correction
siemens/ix pull request #470
Opened 2023-03-28 13:58 UTC by goncalosard

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [x] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [x] Bug fix
- [ ] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Old style:

![image](https://user-images.githubusercontent.com/63813420/228259388-6eafa96e-b68c-477a-a6d7-09d768a14780.png)

Selected style is not correct according to Figma.
When item is selected, then dropdown is closed and reopened, item no longer shows clicked.
When item is selected and the dropdown is closed, it puts header selected.
Also GitHub Issue Number: #416 

## What is the new behavior?

- Added new style for selected header and item
- Item still shows as selected after dropdown is closed and reopened
- After selecting item and closing dropdown, header no longer goes as selected
- When header is selected, it no  longer moves content alignment

New style:

![image](https://user-images.githubusercontent.com/63813420/228259085-48b46a74-955d-4a91-ae41-e97a6063e3a2.png)

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Testing

## Other information

2023-03-29 09:40 UTC, nuke-ellington requested changes
- [x] Click on header shoud deselect group items
- [x] Focus border was lost (@silviowolf will update to latest design spec)

2023-03-30 11:37 UTC, goncalosard commented
@danielleroux @nuke-ellington 
Latest commit has the following changes:
- When header is selected, items are deselected.
- Focus-visible fix
- When there is no items, icon arrow is hidden. (MutationObserver added in case the user removes all items or it has no items and the user adds a item. The component needs to know if the lenght of items from the slot changed so it can update the hide or show of the icon if the slot size changed).

2023-03-31 06:05 UTC, danielleroux requested changes

2023-03-31 06:05 UTC, danielleroux commented on packages/core/src/components/group/group.scss
> +      border-radius: 4px 4px 0px 0px;
use `--theme-default-border-radius`

`border-radius: var(--theme-default-border-radius) var(--theme-default-border-radius) 0px 0px;`

2023-03-31 06:05 UTC, danielleroux commented on packages/core/src/components/group/group.scss
> +    min-width: 24px;
use rem

2023-03-31 06:20 UTC, danielleroux commented on packages/core/src/components/group/group.tsx
> +      this.slotSize = this.groupItems.length;
slotSize is nerver used again in the component? Do you have any local changes which are not pushed?

2023-03-31 06:24 UTC, danielleroux requested changes

2023-03-31 06:24 UTC, danielleroux commented on packages/core/src/components/group/group.tsx
> +  itemSelected = false;
`itemSelected` is used inside `reactive typescript` part here is missing a `@State`

2023-03-31 06:25 UTC, danielleroux requested changes

2023-03-31 06:25 UTC, danielleroux commented on packages/core/src/tests/group/group.e2e.ts
> +    await page.locator('.btn-expand-header .sc-ix-icon-h').click();
`.sc-ix-icon-h ` is a compiler generated class you should not use it as an selector

2023-04-06 05:20 UTC, danielleroux approved these changes

2023-04-13 12:27 UTC, nuke-ellington approved these changes
lgtm

2023-04-14 05:18 UTC, merged