fix(core/category-filter): options
siemens/ix pull request #479
Opened 2023-04-04 13:42 UTC by goncalosard

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [ ] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [x] Bug fix
- [ ] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: #381 

## What is the new behavior?

- Now, when a option is selected for a Category, other category options are not affected.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Testing

## Other information

2023-04-06 08:53 UTC, nuke-ellington commented on packages/core/src/components/category-filter/category-filter.tsx
> +      (token) => token.value === value && token.id === this.category
What happens if no categories are configured?

2023-04-06 08:53 UTC, nuke-ellington commented on packages/core/src/components/category-filter/category-filter.tsx
> -    if (this.filterTokens.find((value) => value?.value === newToken)) {
Why is this check not necessary?

2023-04-11 07:48 UTC, nuke-ellington requested changes
To me it looks like the changes don't have the desired effect. This state should not be possible via
 user input:
<img width="500" alt="Screenshot 2023-04-11 at 09 46 07" src="https://user-images.githubusercontent.com/14405078/231092227-3334b2ca-0b0b-4858-8efc-e3fd3a9e8e88.png">

2023-04-12 14:24 UTC, goncalosard commented
@nuke-ellington commited a fix for it, should be good now.

2023-04-17 11:55 UTC, nuke-ellington approved these changes
lgtm

2023-04-18 05:26 UTC, merged