fix(core/form-controls): Input, Select, Textarea readonly states
siemens/ix pull request #485
Opened 2023-04-10 15:37 UTC by goncalosard

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [x] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [x] Bug fix
- [ ] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue [IX-143]

## What is the new behavior?

- Placeholder are hidden when readonly is active
- Changed cursor style to default when readonly is active

All other topics mentioned on the issue, look already correct.

## Code tested

        <form class="needs-validation m-2">
          <input
            class="form-control"
            defaultValue=""
            placeholder="Enter text here"
            type="text"
            readonly
          />
        </form>

        <ix-select readonly selected-indices="1">
          <ix-select-item label="Item 1" value="1"></ix-select-item>
          <ix-select-item label="Item 2" value="2"></ix-select-item>
          <ix-select-item label="Item 3" value="3"></ix-select-item>
          <ix-select-item label="Item 4" value="4"></ix-select-item>
        </ix-select>

        <textarea
          class="form-control"
          placeholder="Enter text here"
          readonly
        ></textarea>

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Testing

## Other information

2023-04-11 07:50 UTC, nuke-ellington requested changes

2023-04-11 07:55 UTC, danielleroux requested changes
Overall we should a testcases (visual regression) to test all readonly states

2023-04-11 07:55 UTC, danielleroux commented on packages/core/src/components/select/select.tsx
> +    else return this.i18nPlaceholder;
No else needed here. Just a personal opinion 

```typescript
if (this.editable) {
  return this.i18nPlaceholderEditable;
}

if (this.readonly) {
  return '';
}

return this.i18nPlaceholder;
```

is better readable.

2023-04-13 09:04 UTC, nuke-ellington approved these changes
lgtm

2023-04-14 05:17 UTC, merged