fix(core/menu): new width
siemens/ix pull request #514
Opened 2023-05-04 15:02 UTC by goncalosard

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [x] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [x] Bug fix
- [ ] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

[IX-74]

## What is the new behavior?

- Changed width to the new size
- Adapted basic-navigation, map-navigation, menu-about-news, menu-avatar, menu-item to the changed menu width

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Testing

## Other information

2023-05-05 08:55 UTC, nuke-ellington reviewed
The margin values look a little strange to me (e.g. 3.27rem instead of 3.25rem). Is that on purpose?

2023-05-05 10:52 UTC, goncalosard commented
> The margin values look a little strange to me (e.g. 3.27rem instead of 3.25rem). Is that on purpose?

If its 3.25rem, it will not be perfectly aligned with the ix-menu, meaning some pixels will go under it.

2023-05-12 05:15 UTC, danielleroux requested changes
- [ ] Visual issues
- [ ] We should also improve the visual regression tests.

## About News

Not aligned correnlty in expand state:
![image](https://github.com/siemens/ix/assets/2144313/5fd01a07-8cc6-4cf6-9174-a1f142fd754a)

## Menu Overlay

Gap on the right side:

![image](https://github.com/siemens/ix/assets/2144313/a4694be1-607d-47b6-8362-115b91912ccf)

## Menu Avatar

Hover is not correct aligned anymore

![image](https://github.com/siemens/ix/assets/2144313/aad50808-f366-4a7f-be7e-656cd0eb0656)

2023-05-22 06:12 UTC, danielleroux approved these changes

2023-05-22 06:13 UTC, merged