feat(core/cards): add card variation
siemens/ix pull request #542
Opened 2023-05-22 11:36 UTC by danielleroux

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [ ] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bug fix
- [x] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the new behavior?

- Add Card
- Add PushCard
- Add ActionCard
- Add CardList

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2023-05-25 14:04 UTC, nuke-ellington requested changes
Some minor edits

2023-05-25 14:04 UTC, nuke-ellington commented on packages/core/src/tests/push-card/basic/index.html
> +      ix-action-card {
ix-push-card

2023-05-26 08:22 UTC, danielleroux commented on packages/core/src/components/card-accordion/card-accordion.tsx
> +const getAriaControlsId = (prefix: string = 'expand-content') => {
Changed to `@Event() accordionExpand: EventEmitter<CardAccordionExpandChangeEvent>;`

2023-05-26 08:24 UTC, danielleroux commented on packages/core/src/components/card-list/card-list.tsx
> +    if (this.listStyle === 'stack' || this.listStyle === 'scroll') {
Previous integration we implemented also a card-list in the style of a css grid. This will come with the next enhancement.

2023-05-26 08:33 UTC, danielleroux commented on packages/core/src/components/layout/css-grid/css-grid.tsx
> +      return this.findNextTemplate(this.mediaQueries[typeIndex + 1].name);
Component will not be used at the moment also will be marked as `@internal`. Alternative remove it entirely. Any opinion?

2023-05-26 11:41 UTC, nuke-ellington commented on packages/core/src/components/layout/css-grid/css-grid.tsx
> +      return this.findNextTemplate(this.mediaQueries[typeIndex + 1].name);
If we don't need it kick it. If it is likely to be used in the future it can stay :)

2023-05-26 11:53 UTC, nuke-ellington commented on packages/core/src/components/card-list/card-list.tsx
> +                    There are {this.numberOfOverflowingElements} more cards
Probably only through rewording (e.g. 'More cards available (12)').

2023-05-26 11:54 UTC, nuke-ellington approved these changes
lgtm

2023-05-30 12:50 UTC, merged