feat(core/toggle): component rework
siemens/ix pull request #568
Opened 2023-05-31 14:16 UTC by goncalosard

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [x] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [x] Bug fix
- [x] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

[IX-79]

## What is the new behavior?

- Updated the style according to Figma
- Updated the VRT
- Added Checked and Indeterminate examples to the documentation.
- Fixed bug with the width, now width is fit-content and no longer extends to the max size of the window.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2023-06-15 10:11 UTC, nuke-ellington requested changes

2023-06-15 10:11 UTC, nuke-ellington commented on packages/core/src/components/toggle/toggle.scss
> -      );
!important not needed IMO

2023-06-15 10:11 UTC, nuke-ellington commented on packages/core/src/components/toggle/toggle.scss
> +      ) !important;
Same as above

2023-06-15 10:11 UTC, nuke-ellington commented on packages/core/src/components/toggle/toggle.scss
> +:focus-within {
Use focus-visible and merge with above statement into mixin?

2023-06-15 10:11 UTC, nuke-ellington commented on packages/core/src/tests/toggle/toggle.e2e.ts-snapshots/toggle-basic-1-chromium---theme-classic-dark-linux.png
There appears to be a contrast issue with the classic theme?

2023-06-15 14:27 UTC, goncalosard commented on packages/core/src/tests/toggle/toggle.e2e.ts-snapshots/toggle-basic-1-chromium---theme-classic-dark-linux.png
None of the color variables where changed. The only affecting change is that the slider circle lost its border as its intended in the new design following figma.

2023-06-16 08:44 UTC, nuke-ellington commented on packages/core/src/tests/toggle/toggle.e2e.ts-snapshots/toggle-basic-1-chromium---theme-classic-dark-linux.png
This will have to be fixed in the theme. We can merge this PR once the colors are fixed.

2023-06-27 12:15 UTC, danielleroux commented on packages/core/src/tests/toggle/toggle.e2e.ts-snapshots/toggle-basic-1-chromium---theme-classic-dark-linux.png
JSON Token already fixed. Theme generation is required. I will do this asap.

2023-07-17 10:47 UTC, danielleroux commented on packages/core/src/tests/toggle/toggle.e2e.ts-snapshots/toggle-basic-1-chromium---theme-classic-dark-linux.png
@nuke-ellington @goncalosard I updated the theme files (vrt snapshots). Please review the changes. The new theme file contains additonal variables which are not used in code. Is this covered with the PR?

2023-07-19 08:04 UTC, danielleroux approved these changes

2023-07-27 13:09 UTC, nuke-ellington approved these changes
lgtm

2023-07-27 13:11 UTC, merged