feat(core/link-button): new Link Button component
siemens/ix pull request #580
Opened 2023-06-14 16:40 UTC by goncalosard

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [x] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bug fix
- [x] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

[IX-89]

## What is the new behavior?

- Implemented new component Link Button
- Added VRT for basic and disabled
- Added documentation page

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2023-06-15 08:32 UTC, danielleroux requested changes

2023-06-15 08:32 UTC, danielleroux commented on packages/core/src/components/link-button/link-button.tsx
> +
```suggestion

/**
 * @since 1.7.0
 */
```

2023-06-15 08:32 UTC, danielleroux commented on packages/core/src/components/link-button/link-button.tsx
> +  @Prop() url: string = undefined;
```suggestion
  @Prop() url: string;
```

2023-06-16 08:58 UTC, nuke-ellington requested changes

2023-06-16 08:58 UTC, nuke-ellington commented on packages/core/src/components/link-button/link-button.tsx
> +          title={this.disabled ? undefined : this.url}
Why does the disabled button not get the tooltip?

2023-06-16 08:58 UTC, nuke-ellington commented on packages/core/src/components/link-button/link-button.tsx
> +          href={this.disabled ? undefined : this.url}
Same as above

2023-06-16 08:58 UTC, nuke-ellington commented on packages/core/src/tests/link-button/basic/index.html
> +    ix-button {
Dead selector

2023-06-16 08:58 UTC, nuke-ellington commented on packages/core/src/components/link-button/link-button.scss
> +  min-width: 4.2rem;
Value seems odd. Maybe setting it to something like $x-large-space would be better?

2023-06-16 08:58 UTC, nuke-ellington commented on packages/core/src/components/link-button/link-button.scss
> +    &:hover {
With the hover mixin the disabled block would not be necessary?

2023-06-16 08:58 UTC, nuke-ellington commented on packages/core/src/components/link-button/link-button.scss
> +        &.disabled {
Same as above

2023-06-16 08:58 UTC, nuke-ellington commented on packages/core/src/components/link-button/link-button.scss
> +    outline: 1px solid #199fff;
Can we use a custom property for the outline color?

2023-06-23 05:26 UTC, danielleroux requested changes

2023-06-23 05:26 UTC, danielleroux commented on packages/core/src/components/link-button/link-button.scss
> +    @include active {
The `&` selector in combination with `:host` on the first level will not work. I created a ghist regarding major changes between scoped and shadow https://gist.github.com/danielleroux/8812ce6ec2ea34bc388a2cd53ac1e649

2023-06-28 16:04 UTC, danielleroux approved these changes

2023-06-29 11:43 UTC, nuke-ellington approved these changes
lgtm

2023-06-29 12:55 UTC, merged