feat(documentation/button) loading button example
siemens/ix pull request #583
Opened 2023-06-15 12:06 UTC by goncalosard

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [ ] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bug fix
- [x] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

[IX-250]

## What is the new behavior?

- Added loading button example to Button documentation

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2023-06-16 08:38 UTC, nuke-ellington requested changes

2023-06-16 08:38 UTC, nuke-ellington commented on packages/angular-test-app/src/preview-examples/button-loading.ts
> +    <ix-button id="btn" (click)="loading()" class="m-1" variant="Secondary">
There should be three variations of the loading button scenario:

1. Button with text (already done)
2. Button with icon + text
3. Icon button

2023-06-16 08:38 UTC, nuke-ellington commented on packages/angular-test-app/src/preview-examples/button-loading.ts
> +      'Loading... <ix-spinner variant="secondary" size="small"></ix-spinner>';
The order should be the other way around:

<ix-spinnter /> Loading

2023-06-23 14:44 UTC, goncalosard commented
@nuke-ellington @danielleroux New loading button was added with the new props. Documentation examples were also added.
No VRT was added because of moving spinner, making it always fail.

2023-06-28 14:04 UTC, danielleroux commented
Changed the PR to a breaking change.

I have replaced the spinner animation with a new one which fits better into the library. Final adaptions regarding the animation will be done maybe later on.

Removed the type from the interface of the spinner

Add a breaking change section to the document.

2023-06-28 14:35 UTC, merged