fix(core/date-picker): ranged default value
siemens/ix pull request #625
Opened 2023-07-11 15:14 UTC by goncalosard

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [x] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [x] Bug fix
- [ ] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

[IX-101]

## What is the new behavior?

- Changed default value to when range is true, default value is null.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2023-07-19 08:26 UTC, nuke-ellington requested changes

2023-07-19 08:26 UTC, nuke-ellington commented on packages/core/src/components/date-picker/date-picker.tsx
> +    if (this.from === DateTime.now().toFormat(this.format) && this.range) {
Why is the now check necessary here?

2023-08-03 13:26 UTC, nuke-ellington commented on packages/core/src/components/date-picker/date-picker.tsx
> +    if (this.from === DateTime.now().toFormat(this.format) && this.range) {
Resolving this since there will be no default dates anymore.

2023-09-19 10:32 UTC, danielleroux commented
Will be refactored with #737

2023-09-19 10:32 UTC, closed without merging