fix(core/workflow-steps): onStepSelected event
siemens/ix pull request #626
Opened 2023-07-11 16:48 UTC by goncalosard

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [ ] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [x] Bug fix
- [ ] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

[IX-314]

## What is the new behavior?

- Now onStepSelected works correctly emiting the index of the selected step.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2023-07-12 07:57 UTC, nuke-ellington requested changes
Unit test case missing

2023-07-25 05:53 UTC, danielleroux requested changes
Fix not working:

```tsx
        <ix-workflow-steps
          onStepSelected={(event) => {
            console.log(event.detail);
          }}
        >
          <ix-workflow-step>Step 0</ix-workflow-step>
          <ix-workflow-step>Step 1</ix-workflow-step>
          <ix-workflow-step>Step 2</ix-workflow-step>
        </ix-workflow-steps>
```

Should print the index of the step.

2023-08-03 09:29 UTC, danielleroux approved these changes

2023-08-03 13:24 UTC, nuke-ellington requested changes
Small change - lgtm otherwise

2023-08-03 13:24 UTC, nuke-ellington commented on BREAKING_CHANGES.md
> +on the base of different user feedbacks.
```suggestion
Progression of the workflow steps has to be handled by the business logic now. This change is due to various user feedback.
```

2023-08-03 14:21 UTC, nuke-ellington approved these changes
lgtm

2023-08-03 14:47 UTC, merged