Feat/information bar
siemens/ix pull request #637
Opened 2023-07-18 11:57 UTC by marci1501

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [ ] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bug fix
- [ ] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Testing

## Other information

2023-07-19 07:29 UTC, danielleroux requested changes
## To do's

- [ ] Add SPDX Header to new files if not present
```
/*
 * SPDX-FileCopyrightText: 2023 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
```
- [ ] Add TestApp Examples (Angular/React/Vue)
- [ ] Add Documentation page

2023-07-19 07:29 UTC, danielleroux commented on packages/core/src/components/information-bar/information-bar.tsx
> +  tag: 'information-bar',
```suggestion
  tag: 'ix-information-bar',
```

If suggestion is applied all test cases has also to be adapted unit und snapshottests.

2023-07-19 07:29 UTC, danielleroux commented on packages/core/src/components/information-bar/information-bar.tsx
> +  @Prop() bar: BarNumbers[] = [];
Missing JSDoc comment for Prop decorated variables.

```suggestion
  /**
   * Configuration of the bar
   */
  @Prop() bar: BarNumbers[] = [];
```

2023-11-21 15:07 UTC, nuke-ellington commented
> ## To do's
> * [ ]  Add SPDX Header to new files if not present
> 
> ```
> /*
>  * SPDX-FileCopyrightText: 2023 Siemens AG
>  *
>  * SPDX-License-Identifier: MIT
>  *
>  * This source code is licensed under the MIT license found in the
>  * LICENSE file in the root directory of this source tree.
>  */
> ```
> 
> * [ ]  Add TestApp Examples (Angular/React/Vue)
> * [ ]  Add Documentation page
> 
> _**Notice:**_ _**TestApp and Documentation can be implemented afterwards from the core team**_

@marci1501 will you be able to add the missing headers? The iX team will then take care of the other open points.

2023-11-22 09:08 UTC, marci1501 commented
> > ## To do's
> > 
> > * [ ]   Add SPDX Header to new files if not present
> > 
> > ```
> > /*
> >  * SPDX-FileCopyrightText: 2023 Siemens AG
> >  *
> >  * SPDX-License-Identifier: MIT
> >  *
> >  * This source code is licensed under the MIT license found in the
> >  * LICENSE file in the root directory of this source tree.
> >  */
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * [ ]   Add TestApp Examples (Angular/React/Vue)
> > * [ ]   Add Documentation page
> > 
> > _**Notice:**_ _**TestApp and Documentation can be implemented afterwards from the core team**_
> 
> @marci1501 will you be able to add the missing headers? The iX team will then take care of the other open points.

Headers should already be there.

2023-11-22 13:14 UTC, nuke-ellington commented
> > > ## To do's
> > > 
> > > * [ ]    Add SPDX Header to new files if not present
> > > 
> > > ```
> > > /*
> > >  * SPDX-FileCopyrightText: 2023 Siemens AG
> > >  *
> > >  * SPDX-License-Identifier: MIT
> > >  *
> > >  * This source code is licensed under the MIT license found in the
> > >  * LICENSE file in the root directory of this source tree.
> > >  */
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > * [ ]    Add TestApp Examples (Angular/React/Vue)
> > > * [ ]    Add Documentation page
> > > 
> > > _**Notice:**_ _**TestApp and Documentation can be implemented afterwards from the core team**_
> > 
> > 
> > @marci1501 will you be able to add the missing headers? The iX team will then take care of the other open points.
> 
> Headers should already be there.

You are right - my bad :-/

2023-11-22 13:26 UTC, nuke-ellington commented
> ## To do's
> * [ ]  Add SPDX Header to new files if not present
> 
> ```
> /*
>  * SPDX-FileCopyrightText: 2023 Siemens AG
>  *
>  * SPDX-License-Identifier: MIT
>  *
>  * This source code is licensed under the MIT license found in the
>  * LICENSE file in the root directory of this source tree.
>  */
> ```
> 
> * [ ]  Add TestApp Examples (Angular/React/Vue)
> * [ ]  Add Documentation page
> 
> _**Notice:**_ _**TestApp and Documentation can be implemented afterwards from the core team**_

Remaining tasks tracked via [IX-643]

2025-02-19 09:02 UTC, danielleroux commented
We closing the PR to cleanup the pull-requests, feel free to reopen the pr if you starting working on the topic again. Thank you.

2025-02-19 09:02 UTC, closed without merging