feat(core/dropdownbutton): migrate to shadow dom
siemens/ix pull request #638
Opened 2023-07-18 14:07 UTC by danielleroux

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [ ] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bug fix
- [x] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: #511 

## What is the new behavior / Open Points?

- [x] Migrated dropdown-button to shadow-dom
- [x] Refactored ix-dropdown-item
- [x] Add ix-dropdown-header
- [x] Removed old `Placements` (See BRAKING_CHANGES.md)
- [x] Fix sub menu behavior
- [ ] Clarify padding in spec of dropdown-item
- [ ] Fix failing vrt

## Does this introduce a breaking change?

- [x] Yes, see BREAKING_CHANGES.md
- [ ] No

2023-07-19 08:19 UTC, nuke-ellington requested changes

2023-07-19 08:19 UTC, nuke-ellington commented on BREAKING_CHANGES.md
> +Submenu append chevron icon automatically to the trigger element, if the trigger element is an ix-dropdown-item.
```suggestion
The submenu now appends a chevron icon automatically to the trigger element, if the trigger element is an ix-dropdown-item.
```

2023-07-19 08:19 UTC, nuke-ellington commented on packages/core/src/components/dropdown-header/dropdown-header.scss
> +  }
```suggestion
```

2023-07-25 07:45 UTC, nuke-ellington commented on packages/core/src/tests/select/select.e2e.ts-snapshots/select-autoplacement-1-chromium---theme-classic-dark-linux.png
Is the left margin of the checkmark correct? Looks very narrow :)

2023-07-25 08:24 UTC, danielleroux commented on packages/core/src/tests/select/select.e2e.ts-snapshots/select-autoplacement-1-chromium---theme-classic-dark-linux.png
Updated please check

2023-07-25 08:28 UTC, nuke-ellington approved these changes
lgtm

2023-07-25 08:41 UTC, merged