feat(core/modal): rework
siemens/ix pull request #648
Opened 2023-07-21 14:45 UTC by danielleroux

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [x] Unit tests (`yarn test`) were run locally and passed
- [x] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bug fix
- [x] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: #511 

## What is the new behavior?

- Replace custom modal implementation with `HTMLDialog`
- Add `ix-modal-header`, `ix-modal-content`, `ix-model-footer` to handle layouting more structured
- Add `showMessage` function to show default messages (into, success, warning, error, question)
- Add `showModalLoading` to loading spinner as modal

## Does this introduce a breaking change?

- [x] Yes, see BREAKING_CHANGES.md
- [ ] No

2023-07-21 14:51 UTC, danielleroux commented on packages/core/src/components/modal/modal.scss
> +}
Have to be imported because at least chrome tries to overwrite it all the time. Have to look in detail to it!

2023-07-21 14:52 UTC, danielleroux commented on packages/core/src/components/modal/modal.scss
> +  }
Just a wild guess. Have to clarify with @silviowolf

2023-07-21 14:54 UTC, danielleroux commented on packages/core/src/components/modal/modal.tsx
> +      );
Native `HTMLDialog.close` accept only string.

2023-07-21 14:55 UTC, danielleroux commented on packages/core/src/components/modal/modal.tsx
> +              }
`HTMLDialog` and `HTMLDialog::backdrop` uses same target element.

2023-07-21 14:59 UTC, danielleroux commented on packages/core/src/components/utils/modal/loading.tsx
> +      }, timeout);
Additional timeout needed to be sure the "slideUp" animation is done. Disabeld animation can be ignored here.

2023-07-26 11:55 UTC, nuke-ellington requested changes
Some minor tings

2023-07-26 11:55 UTC, nuke-ellington commented on BREAKING_CHANGES.md
> +This breaking change only affects the function `modal` which are exported from `@siemens/ix` (not `@siemens/ix-angular` etc).
```suggestion
This breaking change only affects the function `modal` which is exported from `@siemens/ix` (not `@siemens/ix-angular` etc).
```

2023-07-26 11:55 UTC, nuke-ellington commented on BREAKING_CHANGES.md
> +Container is not needed anymore because model system of iX is using `HTMLDialog` as
```suggestion
Container is not needed anymore because the iX modal system is using `HTMLDialog` now as
```

2023-07-26 11:55 UTC, nuke-ellington commented on BREAKING_CHANGES.md
> +- `icon` and `iconColor` is removed, successor is `ix-modal-header` component.
```suggestion
- `icon` and `iconColor` were removed, successor is the `ix-modal-header` component.
```

2023-07-26 11:55 UTC, nuke-ellington commented on BREAKING_CHANGES.md
> +To get a consistent ui design be decided to remove custom backdrops.
```suggestion
To get a consistent UI design we decided to remove custom backdrops.
```

2023-07-26 11:55 UTC, nuke-ellington commented on packages/core/src/components/modal/modal.tsx
> +   * - Return `false` to about in dismissing the modal
about -> abort?

2023-07-26 11:55 UTC, nuke-ellington commented on packages/core/src/components/modal/modal.tsx
> +              const rect = this.dialog.getBoundingClientRect();
Extract fn?

2023-07-26 11:55 UTC, nuke-ellington commented on packages/documentation/docs/controls/modal.md
> +It is highly recommanded to provide the `IxApplicationContext` as part of you application.
```suggestion
It is highly recommended to provide the `IxApplicationContext` as part of your application.
```

2023-07-26 11:55 UTC, nuke-ellington commented on packages/documentation/docs/controls/modal.md
> +How to open a loading is independent from a framework in use. Note that you hve to import the `showLoadingModal` from the core package `@siemens/ix`
```suggestion
How to open a loading modal is independent from the framework in use. Note that you have to import `showLoadingModal` from the core package `@siemens/ix`.
```

2023-07-26 11:55 UTC, nuke-ellington commented on packages/documentation/docs/controls/modal.md
> +How to open a message is independent from a framework in use. Note that you hve to import the `showMessage` from the core package `@siemens/ix`.
```suggestion
How to open a message modal is independent from the framework in use. Note that you have to import `showMessage` from the core package `@siemens/ix`.
```

2023-07-26 11:55 UTC, nuke-ellington commented on packages/documentation/docs/controls/modal.md
> +The `showMessage`-method returns a Listener with the following signature:
```suggestion
The `showMessage` method returns a Listener with the following signature:
```

2023-07-27 07:29 UTC, nuke-ellington approved these changes
😍

2023-07-27 07:43 UTC, nuke-ellington approved these changes
lgtm

2023-07-27 07:55 UTC, merged