feat(core/grid): add grid component
siemens/ix pull request #721
Opened 2023-08-23 10:10 UTC by danielleroux

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [ ] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bug fix
- [x] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Testing

## Other information

2023-09-01 13:20 UTC, nuke-ellington requested changes

2023-09-01 13:20 UTC, nuke-ellington commented on packages/core/src/index.html
> +  <body style="margin: 0px; height: 100vh" class="theme-brand-dark">
on purpose?

2023-09-01 13:20 UTC, nuke-ellington commented on packages/core/src/tests/basic-navigation/basic-navigation.e2e.ts
> +      width: 780,
```suggestion
      width: mediumWidth,
```

2023-09-04 05:35 UTC, danielleroux commented on packages/core/src/components/grid/grid.tsx
> +   * Grid will be displayed without any padding
Wrong jsdocs here

2023-09-04 08:56 UTC, nuke-ellington requested changes
One small remark - sorry :)

2023-09-04 08:56 UTC, nuke-ellington commented on packages/core/src/components/grid/grid.tsx
> +   * Grid will displayed with a fixed width
```suggestion
   * The grid will have a fixed width
```

2023-09-04 11:52 UTC, nuke-ellington approved these changes
lgtm

2023-09-04 11:54 UTC, merged