fix(core/select): filter corrections
siemens/ix pull request #784
Opened 2023-09-25 14:49 UTC by goncalosard

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [ ] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [x] Bug fix
- [ ] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: closes #773 

## What is the new behavior?

- Opening dropdown no longer resets the value typed by the user before opening.
- User is now able to tab into the select, type and then open the dropdown, where the filter works correctly
- If user types when dropdown is open, then if dropdown is closed and re-opened, filter works correctly with what was typed before.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2023-10-17 08:38 UTC, nuke-ellington requested changes
The changes seem fine but the original issue states that the dropdown should open if the user starts typing. This is not adressed yet. Also consider adding unit tests for these scenarios.

2023-10-25 09:20 UTC, nuke-ellington approved these changes

2023-10-25 11:40 UTC, danielleroux requested changes
In closed PR #849, was the following issue adressed #773 which is not solved here.

2023-10-26 12:20 UTC, danielleroux approved these changes

2023-10-31 14:56 UTC, merged