feat(core/date-dropdown): initial commit
siemens/ix pull request #797
Opened 2023-10-03 11:05 UTC by matthiashader

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [ ] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bug fix
- [ ] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Testing

## Other information

2023-10-11 08:10 UTC, nuke-ellington requested changes

2023-10-16 08:16 UTC, matthiashader commented on packages/core/src/components/date-dropdown/date-dropdown.scss
> +  @media screen and (max-width: 500px) {
resolved

2023-10-16 09:29 UTC, matthiashader commented on packages/core/src/components/date-dropdown/date-dropdown.scss
> +  @media screen and (max-width: 500px) {
resolved

2023-10-16 09:30 UTC, matthiashader commented on packages/core/src/components/date-dropdown/date-dropdown.tsx
> +   * @since 1.1.0
resolved

2023-10-16 09:30 UTC, matthiashader commented on packages/core/src/components/date-dropdown/date-dropdown.tsx
> +@Component({
resolved

2023-10-16 09:30 UTC, matthiashader commented on packages/core/src/components/date-dropdown/date-dropdown.tsx
> +   * When set to 'false', only predefined time date range are available for selection.
resolved

2023-11-03 14:31 UTC, nuke-ellington requested changes
Pressing 'Enter' when 'Custom..' is selected will close the dropdown. Datepicker should open instead.

2023-11-06 14:25 UTC, nuke-ellington requested changes

2023-11-06 14:25 UTC, nuke-ellington commented on packages/core/src/components/date-dropdown/date-dropdown.tsx
> +      console.log(this.associatedDateRangeValue);
```suggestion
```

2023-11-06 14:25 UTC, nuke-ellington commented on packages/core/src/components/date-dropdown/date-dropdown.tsx
> +      console.log(from);
```suggestion
```

2023-11-06 14:25 UTC, nuke-ellington commented on packages/core/src/components/date-dropdown/date-dropdown.tsx
> +      console.log(to);
```suggestion
```

2023-11-06 14:25 UTC, nuke-ellington commented on packages/core/src/components/date-dropdown/date-dropdown.tsx
> +
Sorry cannot do multiline suggestion for some reason today :/

```suggestion
```

2023-11-08 08:38 UTC, nuke-ellington approved these changes

2023-11-13 13:06 UTC, nuke-ellington approved these changes

2023-11-13 13:06 UTC, merged

2024-02-12 12:49 UTC, robert-wettstaedt commented
Hello, are there any plans on when this new feature is going to be released in a new version? It's been merged for almost 3 months now.

2024-02-26 06:36 UTC, matthiashader commented
@robert-wettstaedt sorry for keeping you waiting. This component was released with v2.1.0