docs(avatar): add ux styleguide
siemens/ix pull request #854
Opened 2023-10-17 14:15 UTC by silviowolf

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [ ] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bug fix
- [ ] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: N/A

## What is the new behavior?

- Add styleguide documentation for the Avatar component
- Change Avatar image example to show obviously an image
![image](https://github.com/siemens/ix/assets/115155312/6caa1c28-d115-45c2-bb0c-43cc6205b5f6)
- change test-app examples

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Testing

## Other information

2023-10-18 08:40 UTC, danielleroux requested changes

2023-10-18 08:40 UTC, danielleroux commented on packages/html-test-app/src/preview-examples/avatar-image.html
> +  <ix-avatar image="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADUAAAA1CAIAAABuhDQnAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAANaADAAQAAAABAAAAN
This makes the example unreadable. Also react/angular/vue examples are not updated.

2023-10-20 09:49 UTC, danielleroux commented on packages/html-test-app/src/preview-examples/avatar-image.html
> +  <ix-avatar image="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADUAAAA1CAIAAABuhDQnAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAANaADAAQAAAABAAAAN
@silviowolf Maybe this one here will be fine -> https://www.gravatar.com/avatar/00000000000000000000000000000000 but remember to apply this in html-test-app/angular-test-app/react-test-app and vue-test-app

2023-11-09 09:43 UTC, silviowolf commented
@nuke-ellington, Avatar is now ready to merge...

2023-11-13 13:43 UTC, nuke-ellington approved these changes

2023-11-13 14:08 UTC, danielleroux approved these changes

2023-11-13 14:10 UTC, merged