Fix/map nav
siemens/ix pull request #88
Opened 2022-10-21 13:52 UTC by goncalosard

## Summary

Implemented the map navigation page, and set the previews for the page.

## How did you test this change?

Tested locally

2022-10-25 07:56 UTC, danielleroux requested changes
Did you forgot to add the components from the different test-apps, looks like you only added the auto-generated markdowns but not the source files?

- Missing /Users/daniel/dev/oss/ix/packages/react-test-app/src/preview-examples/map-navigation-overlay.tsx
- Missing /Users/daniel/dev/oss/ix/packages/react-test-app/src/preview-examples/map-navigation.tsx
- Missing /Users/daniel/dev/oss/ix/packages/angular-test-app/src/preview-examples/map-navigation-overlay.ts
- Missing /Users/daniel/dev/oss/ix/packages/angular-test-app/src/preview-examples/map-navigation.ts
- Missing /Users/daniel/dev/oss/ix/packages/html-test-app/src/preview-examples/map-navigation.html
- Missing /Users/daniel/dev/oss/ix/packages/html-test-app/src/preview-examples/map-navigation-overlay.html

2022-10-25 13:43 UTC, danielleroux reviewed
@nuke-ellington Can you please have a look if the map-navigation have a problem with the overlay? Looks a little bit broken the map-navigation

<img width="808" alt="image" src="https://user-images.githubusercontent.com/2144313/197789939-8822c9a5-7763-4504-a707-bf42a8a8cc24.png">

2022-10-25 13:44 UTC, danielleroux approved these changes

2022-10-25 14:25 UTC, nuke-ellington commented
@danielleroux I created an issue for the sidebar issues
@goncalosard the main content area in the examples should not be populated with the text "sidebar content"

2022-10-25 14:42 UTC, danielleroux requested changes
After building the branch locally i got changes in the auto-generated files. This should not happen please update files

2022-10-25 14:43 UTC, danielleroux commented
https://github.com/siemens/ix/issues/92

2022-11-03 06:44 UTC, danielleroux requested changes

2022-11-03 06:44 UTC, danielleroux commented on packages/documentation/docs/controls/navigation/map-navigation.md
> +
Not existing anymore

2022-11-03 06:44 UTC, danielleroux commented on packages/html-test-app/src/preview-examples/map-navigation-overlay.html
> +<!--
Is this working not at my side

2022-11-03 08:59 UTC, danielleroux approved these changes

2022-11-03 09:54 UTC, merged