fix(core/menu): fix menu avatar as trigger
siemens/ix pull request #919
Opened 2023-11-16 06:49 UTC by matthiashader

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [ ] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bug fix
- [ ] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Testing

## Other information

2023-11-21 12:50 UTC, nuke-ellington requested changes
Test cases missing

2024-01-11 05:59 UTC, danielleroux requested changes

2024-01-11 05:59 UTC, danielleroux commented on packages/core/src/components/dropdown/dropdown.tsx
> +    if (!defaultPrevented && !this.show) {
In this case toggle can only be prevented if the show is not already shown. This makes for a function "toggle" which change between show=true and show=false no sense.

2024-01-15 13:38 UTC, danielleroux reviewed
Can you also explain why the images are updated? Cannot find a visual indicator for a change.

2024-01-15 13:38 UTC, danielleroux commented on packages/core/src/components/menu-avatar/menu-avatar.tsx
> +  }
What do you want to achieve here?

2024-01-16 06:31 UTC, jul-lam commented
> Can you also explain why the images are updated? Cannot find a visual indicator for a change.

The only plausible explanation appears to be the removal of the line `z-index: var(--theme-z-index-fixed);` within the application header. This modification was essential to address the z-index issue associated with the nested avatar dropdown.

2024-01-30 11:48 UTC, danielleroux commented
#1060

2024-01-30 11:48 UTC, closed without merging