fix(core/menu-about): unwanted behavior on fast tab change
siemens/ix pull request #933
Opened 2023-11-22 05:48 UTC by matthiashader

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [ ] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bug fix
- [ ] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Testing

## Other information

2024-01-08 10:45 UTC, danielleroux reviewed
PR fixes only menu-about but menu-settings contains a similar implementation. Was this also checked?

//EDIT Can you add more information to the PR description

2024-01-08 11:33 UTC, matthiashader commented
> PR fixes only menu-about but menu-settings contains a similar implementation. Was this also checked?
> 
> //EDIT Can you add more information to the PR description

I tried to reproduce it, but could not reproduce the error in the menu-settings:
async delay(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }

  async fastChange() {
    const menuSettings = document.querySelector('ix-menu-settings');
    const menuSettingsShadowRoot = menuSettings.shadowRoot;
    const menuSettingsItems =
      menuSettingsShadowRoot.querySelectorAll('ix-tab-item');

    for (let i = 0; i < 100; i++) {
      for (const elements of Array.from(menuSettingsItems)) {
        await elements.click();
        await this.delay(10);
      }
      console.log(i);
    }
  }

  render() {
    return (
      <Host>
        <ix-basic-navigation>
          <div class="placeholder-logo" slot="logo"></div>
          <ix-menu>
            <ix-menu-settings>
              <ix-menu-settings-item label="Example Setting 1">
                Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed
                diam nonumy eirmod tempor invidunt ut labore et dolore magna
                aliquyam erat, sed diam voluptua. At vero eos et accusam et
                justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea
                takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum
                dolor sit amet, consetetur sadipscing elitr, sed diam nonumy
                eirmod tempor invidunt ut labore et dolore magna aliquyam erat,
                sed diam voluptua. At vero eos et accusam et justo duo dolores
                et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus
                est Lorem ipsum dolor sit amet.
              </ix-menu-settings-item>
              <ix-menu-settings-item label="Example Setting 2">
                Stet clita kasd gubergren, no sea takimata sanctus est Lorem
                ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur
                sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut
                labore et dolore magna aliquyam erat, sed diam voluptua. At vero
                eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
                gubergren, no sea takimata sanctus est Lorem ipsum dolor sit
                amet. Duis autem vel eum iriure dolor in hendrerit in vulputate
                velit esse molestie consequat, vel illum dolore eu feugiat nulla
                facilisis at vero eros et accumsan et iusto odio dignissim qui
                blandit praesent luptatum zzril delenit augue duis dolore te
                feugait nulla facilisi. Lorem ipsum dolor sit amet,
              </ix-menu-settings-item>
            </ix-menu-settings>
          </ix-menu>
        </ix-basic-navigation>
        <ix-button
          onClick={() => {
            this.fastChange();
          }}
        >
          PUSH ME
        </ix-button>
      </Host>

2024-01-17 14:09 UTC, nuke-ellington requested changes

2024-01-17 14:09 UTC, nuke-ellington commented on packages/core/src/components/menu-about/menu-about.tsx
> +    setTab(this, label);
Identical function names are confusing here

2024-02-07 13:57 UTC, nuke-ellington approved these changes

2024-02-08 11:49 UTC, merged