Fix/menu close
siemens/ix pull request #99
Opened 2022-10-28 14:59 UTC by goncalosard

## Summary

It was changed to when a menu item is selected, the menu closes, it also closes the about and legal & setting content.

2022-11-02 06:41 UTC, danielleroux requested changes

2022-11-02 06:41 UTC, danielleroux commented on packages/core/src/components/menu-about/menu-about.tsx
> +  @Event() close: EventEmitter;
This cause a major change in our component api. Is there any reason behind it?

2022-11-02 06:41 UTC, danielleroux commented on packages/core/src/components/menu-item/menu-item.tsx
> +
Is a new event necessary? Why not the default click event?

2022-11-04 10:26 UTC, danielleroux approved these changes

2022-11-07 10:21 UTC, nuke-ellington approved these changes

2022-11-07 10:21 UTC, merged