refactor(core/date|time|datetime): replace dayjs with luxon
siemens/ix pull request #990
Opened 2023-12-11 06:14 UTC by danielleroux

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [ ] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bug fix
- [ ] Feature
- [x] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the new behavior?

Replace dayjs library with luxon to avoid breaking changes

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2023-12-12 09:22 UTC, nuke-ellington requested changes

2023-12-12 10:19 UTC, danielleroux commented on packages/core/src/components/date-dropdown/date-dropdown.tsx
> +      this.closeDropdown();
yes

2023-12-12 10:41 UTC, nuke-ellington approved these changes

2023-12-12 15:55 UTC, nuke-ellington approved these changes

2023-12-13 08:29 UTC, nuke-ellington approved these changes

2023-12-13 08:52 UTC, merged